### ISSUE TITLE
Case Sensitive Search fallback to lowercase

### ISSUE THREAD

**Issue by cellnet** [royqh1979/RedPanda-CPP#107]
前提：代码中同时存在内样的片段内容，只不过它们大小写不同，而之前对同样内容但大小写不一致的内容进行过搜索，比如："NAME", "name"，使用name进行过搜索。
操作：当再次进行搜索时，选中"Case Sensitive"，目的是精确查找，比如"Name"，点击 “Find Next”
期望结果：可以定位到大小写敏感搜索情况下的内容所在位置。
实际结果：由于搜索对话框中存在之前使用过的内容一致且大小写不一致的内容，需要查找的内容会被自动转换成对应的内容来进行搜索，从而无法找出期望结果。

**Comment by cellnet** [comment]
进一步测试发现，如果之前有过大小写不一致的内容，只要leave focus，相应内容就会被切换到对应的大小写不一致，但是内容相同的过去查找时使用的字符串上。

**Comment by cellnet** [comment]
但是通过如果通过添加”空格“等字符强制不同而把不同内容加入后，切换焦点时，不会再次产生搜索内容的替换。
这应该是搜索框的某个设定，这个设定本身应该就是和大小写相关的。所以如果同时存在大小写不同但内容相同的结果时不会出错。但是如果只包含其中一个结果时，另外一个正常输入是无法进行查找的（会被自动切换回不同大小写的同样的内容上去）

**Comment by royqh1979** [comment]
fixed in [627ff08](https://github.com/royqh1979/RedPanda-CPP/commit/627ff08d23e64868fce2ce67410507d88a417b73)
