### ISSUE TITLE
Makefile.win is not correct for C-files

### ISSUE THREAD

**Issue by AlexN-114** [royqh1979/RedPanda-CPP#110]
There are two bugs with the Makefile.win for C-files. No or wrong command is generated. The patch below should help. ;-)

 [aN_Projectcompiler.patch](https://github.com/royqh1979/RedPanda-CPP/files/11166869/aN_Projectcompiler.patch)

**Comment by royqh1979** [comment]
why not sumbit a PR?

**Comment by AlexN-114** [comment]
I am new to Git. I tried a PR, but it didn't work for me.
