### ISSUE TITLE
[Feature Request] Ability to customize the output of console pauser

### ISSUE THREAD

**Issue by tur1ngb0x** [royqh1979/RedPanda-CPP#112]
**Let the user customize the output of console pauser**

Example: Menu Bar > Tools > Options > Console Pauser > General

```
Console Pauser Format
  ( ) Default
  (*) Custom

Enter your custom format
  Return Value: %RETURN
  Time: %TIME
  Memory: %MEMORY
```

**Before (Default)**

```
Hello World !
--------------------------------
Process exited after 0.008 seconds with return value 0, 6144 KB mem used.

Press ANY key to exit...
```

**After (Custom)**

```
Hello World !
--------------------------------
Return Value: 0
Time: 0.008 seconds
Memory: 6144 KB

Press ANY key to exit...

```

**Comment by royqh1979** [comment]
Thanks for the suggestion!

ConsolePauser is a simple c program. Users can easily modify and recompile it. Make it's output configurable only made things complicate and I don't see there's enough reason to justify it.
