### ISSUE TITLE
[BUG] 自动补全

### ISSUE THREAD

**Issue by Tiphereth-A** [royqh1979/RedPanda-CPP#120]
版本 v2.22

键入 `std::ios::sync_with_stdio(false);` 的过程中

1.  只 `#include <iostream>` 而没有 `#include <ios>` 的话不会补全 `std::ios`

    ![1](https://github.com/royqh1979/RedPanda-CPP/assets/62847935/9b42e0c6-b69d-4a04-aa19-4d490bf6375c)

    `#include <ios>` 后才会补全 `std::ios`

    ![2](https://github.com/royqh1979/RedPanda-CPP/assets/62847935/c32a43f3-eac4-4608-8a9d-995e0dc7d1f1)

2.  不会补全 `std::ios::sync_with_stdio`

    ![3](https://github.com/royqh1979/RedPanda-CPP/assets/62847935/635cb4b0-2d9c-4377-bb57-4f46ddbf6223)

**Comment by royqh1979** [comment]
2.23版中已修正
