### ISSUE TITLE
代码完成 改进需求

### ISSUE THREAD

**Issue by sdkljd** [royqh1979/RedPanda-CPP#121]
代码完成能否提供一个顺序匹配选项，现在的这种类似模糊匹配的总是会有大量不需要的弹出
![无标题](https://github.com/royqh1979/RedPanda-CPP/assets/116957851/c9f0a1b9-39e5-4ff9-aff7-a5eadbbe2d91)

第二点是，没隔几个版本便会出现scanf 等一部分不会显示出来，以上图片中能看出来

**Comment by royqh1979** [comment]
不能提示scanf是哪个版本？包含了哪些头文件？

**Comment by sdkljd** [comment]
> 不能提示scanf是哪个版本？包含了哪些头文件？

版本：2.22
系统：windows 10
一个新建的c 空项目默认包含的头文件,还有比如 fscanf 也无法提示(也许不只是这俩个无法提示)

**Comment by sdkljd** [comment]
> 不能提示scanf是哪个版本？包含了哪些头文件？

编译器配置集 能否提供一个全局配置(针对当前编译器下的DEBUG RELEASE，类似CODEBLOCKS的编译器配置方式),有时需要使用外部库等，还得对debug release全部配置一次

**Comment by sdkljd** [comment]
> > > 不能提示scanf是哪个版本？包含了哪些头文件？
> > 
> > 
> > 版本：2.22 系统：windows 10 一个新建的c 空项目默认包含的头文件,还有比如 fscanf 也无法提示(也许不只是这俩个无法提示)
> 
> 空项目默认没有包含任何头文件。肯定无法提示scanf呀。


新建的一个C工程啊，不是空的，自带的模板 ConsoleApp_c.txt 代码啊，您老试试先
