### ISSUE TITLE
样例测试时，错误地将标准错误输出当作了输出的一部分

### ISSUE THREAD

**Issue by ShizuhaAki** [royqh1979/RedPanda-CPP#123]
目前的状态是：标准错误输出和标准输出被混在了一起，这使得要想使用比对样例的功能，必须要记得删去标准错误输出内容，不是非常方便。

这一点上，可以参考 [CP Editor](https://github.com/cpeditor/cpeditor) 的设计——标准错误输出和编译器输出放在一起。

![CP Editor](https://cpeditor.org/img/banner/home-center-2.jpg)

**Comment by royqh1979** [comment]
打比赛很少会有人在程序里往stderr写东西吧？

**Comment by ShizuhaAki** [comment]
那比对答案的时候似乎也应该不考虑stderr的内容来比对（我个人是用条件编译在提交时不输出stderr的）

**Comment by royqh1979** [comment]
2.23的试题集选项中增加 “将标准输出重定向到工具输出面板” 选项（缺省关）
