### ISSUE TITLE
Trivial typos on english language

### ISSUE THREAD

**Issue by sangiye0** [royqh1979/RedPanda-CPP#124]
Hi, I found some typos on english Compiler options menu, version 2.23.

Tools > Options > Environment > Appearence
Appear**e**nce -> Appearance (correct)

Tools > Options > Environment > Appearence > Theme
Contra**c**t -> Contrast (correct)

Tools > Options > Environment > File Association
Independ**a**nt -> Independent (correct)

Tools > Options > Editor > Auto save > Objects to save
open**n**ed -> opened (correct)

Tools > Options > Code Formatter > General > Other 2
multi**m**ple -> multiple (correct)

**Comment by royqh1979** [comment]
Thanks for the bug report
