### ISSUE TITLE
从软件帮助里跳转到的小熊猫dev404

### ISSUE THREAD

**Issue by sanxiadaba** [royqh1979/RedPanda-CPP#133]
![image](https://github.com/royqh1979/RedPanda-CPP/assets/79378747/391d6449-dc8f-466f-9424-38245ebc8538)
![image](https://github.com/royqh1979/RedPanda-CPP/assets/79378747/4cb75006-7442-4a2e-ab8f-4eea4d6eb2d8)
![image](https://github.com/royqh1979/RedPanda-CPP/assets/79378747/715edd6a-1bdb-4a50-b0a9-c997921c57d5)

**Comment by royqh1979** [comment]
因原网站域名被gitee禁用（网站的图标被某索引网站外链），因此使用新的网址。
小熊猫C++软件新官网：
http://royqh.net/redpandacpp/

不为这个专门发新版了
