### ISSUE TITLE
gdb调试时使用freopen会无法读入文件

### ISSUE THREAD

**Issue by hyj0824** [royqh1979/RedPanda-CPP#157]
## 问题描述

在动态单步调试时，发现cin/scanf无法从freopen重定向中读入，编译选项为 `-std=c++14 -Wall -Wextra -Wl,--stack=333333333 -Wshadow -g3 -Og`。请问是ide的问题还是gdb的问题？我使用dev-cpp 5.11以及其他ide都是可以正常读入的。且与流同步应该无关。

## 问题截图

![image](https://github.com/royqh1979/RedPanda-CPP/assets/50772730/e4a9b4b1-abc4-44e4-ae86-8b126f6391ad)

**Comment by hyj0824** [comment]
好吧，找到问题了，不能开 `-Og`。

**Comment by royqh1979** [comment]
不调试直接运行，读入的数据正确吗？



Frank Yu ***@***.***> 于2023年11月9日周四 20:16写道：

**Comment by hyj0824** [comment]
直接运行是可以读取到文件内容的。从终端输入数据也没有问题。只是在gdb+freopen时才会这样。

**Comment by West-Pavilion** [comment]
从2.22版本以后，用图形界面调试时，单步运行fopen函数读取文件得不到正确的FILE指针，根本原因是调试的时候，文件搜索路径是gdb.exe所在的目录，所以必须用绝对路径才能打开正确的文件。

但是直接运行确实能够得到正确的结果，可能是从2.22版本以后gdb的某项参数传错了，没有把调试时文件搜索根目录设置成 源代码/可执行文件 所在目录。

附上SourceForge的两个版本下载链接：

[2.22版本](https://sourceforge.net/projects/redpanda-cpp/files/v2.22/RedPanda.C++.2.22.win64.MinGW-w64.X86_64.GCC.11.2.Portable.7z/download)

[2.23版本](https://sourceforge.net/projects/redpanda-cpp/files/2.23/RedPanda.C++.2.23.win64.MinGW-w64.X86_64.GCC.13.1.Portable.7z/download)

下面是复现代码以及测试文件：

[fuxian.zip](https://github.com/royqh1979/RedPanda-CPP/files/13399101/fuxian.zip)

**Comment by royqh1979** [comment]
嗯，最新版里已经处理了这个问题

West-Pavilion ***@***.***> 于2023年11月18日周六 13:35写道：
