### ISSUE TITLE
2.25 版本使用 freetype 作为 Windows 字体引擎导致 UI 字体模糊

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#159]
**问题描述：**
最近一次更新（2.25）中，开发者决定在 Windows 系统中使用 freetype 作为字体引擎，以替代之前的 旧版本 字体引擎。然而，这一改动导致了新版本的程序中 UI 字体显示有一定程度的模糊，给用户带来了不适的感觉。

**对比图：**
为了更清晰地展示问题，我提供了新版本和上一个版本的对比图。

**上一个版本（2.24）：**

![上一个版本截图](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/1c381158-085c-4e10-ae02-b1379e4782e0)

**新版本（2.25）：**

![新版本截图](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/34e4ff8c-ccce-496e-a756-0ffcd5fbb790)
（顶部菜单的“视图”的“图”字，“冬”下面的两点都合在一起了）
（文件导航视图里，“度”字，广字头里面的“廿”左边那一竖没出头）
（新版本的ui文字加粗和加黑了，整体美观度下降）

**问题影响：**
1. 字体模糊：新版本中使用的 freetype 在 Windows 上渲染字体时，似乎导致了一定程度的模糊，尤其是在小字体和细节处。
2. 用户体验下降：这种模糊可能影响用户的整体体验，特别是对于注重细节的用户而言。

**建议解决方案：**
1. **字体优化：** 考虑优化 freetype 的设置，以确保在 Windows 系统上呈现的字体清晰可见。
2. **用户选择：** 考虑在程序设置中添加一个选项，让用户可以在 freetype 和 旧版本 之间选择，以满足不同用户的偏好。
3. **文档更新：** 在更新的文档中详细说明这一改动，并提供解决模糊字体的方法，以便用户自行调整。

**其他信息：**
- **操作系统：** Windows 10 家庭中文版    版本号:21H2    操作系统内部版本:19044.3086
- **程序版本：** 小熊猫 C++ 2.25.1
- **屏幕分辨率：** 1920x1080

这个问题的解决将有助于提高用户对程序的满意度，期待开发团队尽快处理。感谢您的关注与支持！

**Comment by royqh1979** [comment]
感谢提议。
由于：
1. 在qt5中指定是否使用freetype作为文字引擎，必须在创建QApp之前
2. 小熊猫必须创建QApp之后才能使用Qt的相关接口读取配置参数。
所以目前暂时无法将文字引擎的选择做成可配置选项。

West-Pavilion ***@***.***> 于2023年11月17日周五 21:15写道：

**Comment by royqh1979** [comment]
新版改为使用qt.conf文件来控制是否使用freetype引擎。


West-Pavilion ***@***.***> 于2023年11月18日周六 23:12写道：
