### ISSUE TITLE
Please add support for Microsoft Visual C++ compiler (cl.exe)

### ISSUE THREAD

**Issue by GidNT5** [royqh1979/RedPanda-CPP#162]
I am using the Microsoft Visual Studio compiler with RedPanda-CPP.
The compiler is not "installed" on my system.
It's just located in a folder on my drive.
I can configure RedPanda-CPP to use it.
It will correctly pass these custom commands when entered in the box at the compiler set configuration:
 "/nologo /std:c++17 /O2 /EHsc"

However, the program passes Linux style commands to the compiler when I add the file paths to the includes and libraries and cl.exe does not understand them.
It expects '/I' and '/LIBPATH:', but the IDE sends '-I' and 'L' instead.

When I enter '/link /LIBPATH:"D:/RedPanda-CPP/MSVC/14.38.33130/lib/x64" /I"D:/RedPanda-CPP/MSVC/14.38.33130/include"' in the box I get the following message in the compile log:

LINK : warning LNK4044: unrecognized option '/ID:/RedPanda-CPP/MSVC/14.38.33130/include'; ignored

**Comment by GidNT5** [comment]
Yay!
I managed to get rid of the warning by modifying the arguments when calling the compiler.

/I"D:/RedPanda-CPP/MSVC/14.38.33130/include"
/nologo /std:c++17 /O2 /EHsc
/link /LIBPATH:"D:/RedPanda-CPP/MSVC/14.38.33130/lib/x64" User32.lib Gdi32.lib

It would be nice if one could add the libraries and the includes under the tab "directories" instead.
At the moment this is not supported yet.

**Comment by iahung2** [comment]
As I know, this IDE only supports MinGW. How could you get it to work with MSVC? I'm really curious.
