### ISSUE TITLE
[RFC] 优化 “点击代码格式化按钮后，不移除断点” 

### ISSUE THREAD

**Issue by hui-shao** [royqh1979/RedPanda-CPP#19]
## 背景
在 debug 过程中，常常下断点。
但是点击 "代码格式化" 按钮之后，断点会被自动清除。

## 预期
希望实现 “点击代码格式化按钮后，不移除断点”。

**Comment by royqh1979** [comment]
因为代码格式化之后，代码本身的行数可能会发生变化（比如 if () {的{移动到下一行），导致断点的位置失效
所以没有办法实现

**Comment by hui-shao** [comment]
> 因为代码格式化之后，代码本身的行数可能会发生变化（比如 if () {的{移动到下一行），导致断点的位置失效
> 所以没有办法实现

确实，代码行数变化的问题是存在的，实现起来有难度。

我想我们可以换个思路。

实际情况中，大部分代码的行不会变化。
我的建议是，可以不清除短点，这样一来，使用者可以只需要修改部分断点位置，无需重新打一遍所有断点。

仅作建议，作者可以考虑下哈

希望 RedPanda 越来越好！
