### ISSUE TITLE
对命名空间里的变量使用 using 声明，编辑器不会给出其补全提示

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#192]
对命名空间里的变量使用 using 声明，编辑器不会给出其补全提示

同样，使用 using std::cin 和 using std::cout 声明后，编辑器也不会给出其函数补全提示，即使 ctrl + click 查看其定义可以跳转到正确的位置

![屏幕截图(178)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/6623de89-91d6-4a7a-9e15-8488148e9d16)

![using 声明](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/159dda7d-c5ea-460a-8579-fe8a14bbb409)

以下是对应的测试代码：

[对命名空间里的变量使用 using 声明，编辑器不会给出其补全提示.zip](https://github.com/royqh1979/RedPanda-CPP/files/14354969/using.zip)

**Comment by Ltabsyy** [comment]
已修正？
