### ISSUE TITLE
在 scanf 等函数中，对于形如 &structure 的表达式，不应将其分析为指针类型

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#195]
当使用 scanf 函数读取一个结构体对象的成员数值时，通常需要加上取址符 '&', 但此时编辑器会将其分析为指针类型，无法通过成员访问符 '.' 获取可选的成员列表

事实上，成员访问符 '.' 和 '->' 的运算符优先级比取址符 '&' 高，所以应该仅在

1. 对象本身是指针类型时；
2. 仅当取址符与结构体对象被括号包围时；

才应将其分析为指针类型 

![屏幕截图(185)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/67ff34a1-9ed4-43db-911c-2e2f43adb695)

![屏幕截图(186)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/39dfe0f2-9572-4aa4-9928-75222f317c4c)

下面是对应的测试代码：

[在 scanf 等函数中，对于形如 &structure 的表达式，不应将其分析为指针类型.zip](https://github.com/royqh1979/RedPanda-CPP/files/14355708/scanf.structure.zip)

**Comment by Ltabsyy** [comment]
不建议写出这种有歧义的代码，小熊猫这点可以不改
