### ISSUE TITLE
编辑器的悬停提示会把 C语言 的结构体当做 C++ 的类来分析

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#200]
编辑器的悬停提示会把 C语言 的结构体当做 C++ 的类来分析

在 C语言 文件中，将鼠标悬停在结构体成员变量上时，会发现编辑器的类型提示是以 C++ 的标准给出的。

然而，C语言 中没有 public 修饰符，作用域解析运算符 '::' ，也没有 __dummy__ 修饰符，这些词语不应该在 C语言 文件的悬停提示中出现。

另，C++中也没有这个 __dummy__ 修饰符

![屏幕截图(204)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/0efaea8a-e326-4bc2-afa1-8540b25d10a1)

下面是对应的测试代码：

[编辑器的悬停提示会把 C语言 的结构体当做 C++ 的类来分析.zip](https://github.com/royqh1979/RedPanda-CPP/files/14357198/C.C%2B%2B.zip)

**Comment by Ltabsyy** [comment]
C语言没有，那就认为它有，以表示元素为结构体元素，typedef struct的typedef前名以typedef后名加__dummy__显示
