### ISSUE TITLE
编辑器的提示中局部作用域中的结构体定义过早地隐藏了全局作用域中的同名结构体定义

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#210]
编辑器的提示中局部作用域中的结构体定义过早地隐藏了全局作用域中的同名结构体定义

当全局作用域中的结构体名字与局部作用域中的结构体名字同名时，在局部作用域中，编辑器对结构体变量的成员的提示会依据局部作用域中的定义，即使局部作用域中的同名结构体的定义点在使用点之后

![屏幕截图(213)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/3891ec9a-e946-4d4e-b8fe-b40f7ccbf9a4)

![屏幕截图(212)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/56ff1956-fd71-4fb6-a3a7-2586742992c6)

下面是对应的测试代码：

[编辑器的提示中局部作用域中的结构体定义过早地隐藏了全局作用域中的同名结构体定义.zip](https://github.com/royqh1979/RedPanda-CPP/files/14370755/default.zip)

[编辑器的提示中局部作用域中的结构体定义过早地隐藏了全局作用域中的同名结构体定义_使用 C++ 关键词 typeid 验证类型.zip](https://github.com/royqh1979/RedPanda-CPP/files/14371357/_.C%2B%2B.typeid.zip)

**Comment by royqh1979** [comment]
这种写法容易造成bug，正常来说不会这么写代码。

所以暂时不考虑修正。
