### ISSUE TITLE
在宏名后输入圆括号会导致编辑器认为其是一个仿函数宏，即使实际不是如此

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#212]
在宏名后输入圆括号会导致编辑器认为其是一个仿函数宏，即使实际不是如此

例如，这里定义一个常量宏

```cpp
#define VAR 1
```

之后在使用该常量宏时，如果同时输入一对圆括号，那么编辑器会将其作为一个无参的仿函数宏来进行提示

![屏幕截图(218)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/d4b2309c-5512-4c90-aee5-ede7c11588f2)

这可能会让用户误认为该宏是一个真正的仿函数宏，从而导致开发过程受阻

下面是对应的测试代码：

[在宏名后输入圆括号会导致编辑器认为其是一个仿函数宏，即使实际不是如此.zip](https://github.com/royqh1979/RedPanda-CPP/files/14383162/default.zip)

**Comment by royqh1979** [comment]
已随#213修正
