### ISSUE TITLE
如果使用宏为已有的函数取一个别名，那么该名字不会被识别为函数

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#213]
如果使用宏为已有的函数取一个别名，那么该名字不会被识别为函数

例如，给出如下代码：

```cpp
#define print defined_print
#define rename(i) i##t
#define pr rename(prin)

void defined_print(const char* data){
	std::cout << data << std::endl;
}
```

那么上述代码片段中，`print` `pr` `rename(prin)` 不会被编辑器识别为函数，也不会给出对应的形参列表

![屏幕截图(220)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/a64278ed-831a-462c-b543-517efbc8f08c)

而以此方式使用宏的函数别名定义在 Windows 提供的 API (如 windows.h) 中十分常见

下面是对应的测试代码：

[如果使用宏为已有的函数取一个别名，那么该名字不会被识别为函数.zip](https://github.com/royqh1979/RedPanda-CPP/files/14383254/default.zip)

**Comment by royqh1979** [comment]
已实现此功能
