### ISSUE TITLE
编辑器在对带有宏拼接的宏名进行形参提示时会同时显示当前不生效的版本

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#214]
编辑器在对带有宏拼接的宏名进行形参提示时会同时显示当前不生效的版本

理想的情况是，形参列表提示应只选择当前生效的版本

以头文件 windows.h 中的 MessageBox 函数为例，该函数通过有条件判断的宏拼接定义，即通过判断宏 UNICODE 在包含该头文件时是否已定义来决定具体生效的版本，使用不对应版本的参数进行函数调用会导致程序错误

因此，在编辑器中，未定义 UNICODE 宏时，应当只提示形参列表为

```cpp
int WINAPI MessageBoxA(HWND hWnd,LPCSTR lpText,LPCSTR lpCaption,UINT uType);
```

的函数

而在已经定义 UNICODE 宏且该宏在头文件中生效时，应当只提示形参列表为

```cpp
int WINAPI MessageBoxW(HWND hWnd,LPCWSTR lpText,LPCWSTR lpCaption,UINT uType);
```

的函数

![屏幕截图(221)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/69bad61b-6136-4d37-bc1d-ff4129752a53)

![屏幕截图(222)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/6900d515-b72b-46ef-93b6-daffa37a9671)

下面是对应的测试代码：

[编辑器在对带有宏拼接的宏名进行形参提示时会同时显示当前不生效的版本.zip](https://github.com/royqh1979/RedPanda-CPP/files/14383606/default.zip)

**Comment by royqh1979** [comment]
已修正
