### ISSUE TITLE
滑动水平方向滚动条会导致光标显示到行号区域

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#215]
滑动水平方向滚动条会导致光标显示到行号区域

复现方法：首先将编辑器页面放大至出现水平滚动条，然后将光标放在编辑器的最左边，此时向右滑动水平滚动条会导致光标错位到行号区域。在此状态下，输入一个任意字符，页面自动跳转时跳转到的位置不能看到输入的具体字符

![屏幕截图(223)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/e9e820f6-2dce-4003-8869-31ba29f65f69)

（上图中，光标被错位到第 5 行的行号处）

下面是对应的测试代码：

[滑动水平方向滚动条会导致光标显示到行号区域.zip](https://github.com/royqh1979/RedPanda-CPP/files/14383782/default.zip)

**Comment by royqh1979** [comment]
已修正
