### ISSUE TITLE
查看函数 std::ios::sync_with_stdio() 的定义会导致其从编辑器补全提示中消失

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#218]
查看函数 std::ios::sync_with_stdio() 的定义会导致其从编辑器补全提示中消失

注意，该现象仅在单文件开发时存在，在项目开发时无此现象

打算法的同学可能会使用 std::ios::sync_with_stdio(false) 来取消流同步，但如果该同学好奇该函数函数的定义并尝试去查看时，可能会导致该函数从编辑器的补全提示中消失

例如，使用 ctrl + 鼠标左键 的方式查看 std::ios::sync_with_stdio() 的定义，会导致该函数及大量可选项从编辑器的补全提示中消失

在导致上述结果发生的情况下，可通过如下步骤恢复其补全提示： 
1. 使用 ctrl + 鼠标左键 的方式查看 std::ios 的定义
2. 在跳转到的界面中再次使用 ctrl + 鼠标左键 的方式查看 basic_ios 的定义 
3. 此时，std::ios::sync_with_stdio() 及大量消失的补全提示都恢复了

P.S. 也可以通过重启 小熊猫C++ 或者 关闭所有页面重新载入 的方式解决上述问题

![屏幕截图(229)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/72f81792-7e40-469b-8dd1-5b71ced7d395)

下面是对应的测试代码：

[查看函数 std;;ios;;sync_with_stdio() 的定义会导致其从编辑器补全提示中消失.zip](https://github.com/royqh1979/RedPanda-CPP/files/14384215/std.ios.sync_with_stdio.zip)

注：C++ 头文件 memory 中的 std::shared_ptr 有类似的特性，即查看其实例对象的任意一个函数的定义会导致其所有函数从编辑器的智能补全提示中消失

**Comment by royqh1979** [comment]
std::ios实际是basic_ios<char>，其父类为ios_base
打开ios_base.h时，会自动重新解析ios_base的定义，这会导致basic_ios从ios_base继承的成员信息丢失。

已修正
