### ISSUE TITLE
C++ 的默认实参，浮点数的提示会多显示一个小数点 '.'，字符串不会显示

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#219]
C++ 的默认实参，浮点数的提示会多显示一个小数点 '.'，字符串不会显示，字符也不会显示

给出以下 C++ 代码：

```cpp
void printdouble(double data = 10.6);
void printstring(const char *data = "Hello, World!");
void printchar(char data = 'R');

void printmult(const char *str = "PAN", char data = 'E',int a = 10);

int main() {
	/* 请在小熊猫C++编辑器中将鼠标分别放入下列四个函数的括号中间，查看编辑器的形参提示 */
	printdouble();
	printstring();
	printchar();
	printmult();
}
```

此时，在小熊猫C++ 提示的形参列表中，浮点数的提示会多显示一个小数点，字符串的内容不会被提示

![屏幕截图(235)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/bba7625e-64ce-4ad7-bcf6-471fc108f354)

![屏幕截图(236)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/73d8194d-0182-40be-9cd0-d699bbe8e098)

关于默认实参中字符串不显示的测试代码，还可以尝试使用 C++ 标准库 iomanip 里的 std::quoted 函数，其正好有字符类型的默认实参，同时还可以检测下个版本小熊猫的智能提示对函数声明中下划线 '_' 与 尖括号 '<>' 的支持情况

![屏幕截图(251)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/20797cab-0e7d-4533-a474-7d80759496d6)

下面是对应的测试代码：

[C++ 的默认实参，浮点数的提示会多显示一个小数点 '.'，字符串不会显示 .zip](https://github.com/royqh1979/RedPanda-CPP/files/14394657/C%2B%2B.zip)

**Comment by royqh1979** [comment]
已修正

**Comment by West-Pavilion** [comment]
经测试，在 2.27.2390 版本的 小熊猫C++ 中，默认实参中浮点数的形参提示已正确显示，但是字符串和字符仍然不会显示
