### ISSUE TITLE
编辑器没有对函数 std::ios::sync_with_stdio() 的形参补全提示

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#220]
编辑器没有对函数 std::ios::sync_with_stdio() 的形参补全提示

将鼠标放到函数 std::ios::sync_with_stdio() 的圆括号中间，发现编辑器没有对其形参列表的提示

![屏幕截图(241)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/19797430-c019-405f-85f2-270035f2526c)

但是，如果把鼠标悬停在这个函数名上，会发现编辑器其实已经获取到了它的形参列表，并能够正确显示

![屏幕截图(242)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/ced6a8c8-1386-4810-aa6a-048db1f52614)

下面是对应的测试代码：

[编辑器没有对函数 std;;ios;;sync_with_stdio() 的形参补全提示.zip](https://github.com/royqh1979/RedPanda-CPP/files/14384776/std.ios.sync_with_stdio.zip)

**Comment by royqh1979** [comment]
已修正
