### ISSUE TITLE
在特定风格的多行注释后按回车键，编辑器会自动补一个不需要的星号

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#221]
在特定风格的多行注释后按回车键，编辑器会自动补一个不需要的星号

如果使用如下风格的多行注释，并在注释的结束处按回车键，就会发现编辑器自动补了一个不需要的星号

```cpp
/* 这种风格的多行注释会导致在末尾处按回车键 
 * 自动补一个不需要的星号 */
```

![屏幕截图(246)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/a1238f9e-09ac-41f5-b7ad-403173fc76e9)

![屏幕截图(247)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/478a4bb6-deee-4980-8b50-2994762af112)

然而，在编辑此 issue 的时候，我发现 github 的 markdown 编辑器也有此特性

所以这应该是一个很正常的现象

下面是对应的测试代码：

[在特定风格的多行注释后按回车键，编辑器会自动补一个不需要的星号.zip](https://github.com/royqh1979/RedPanda-CPP/files/14385022/default.zip)

**Comment by royqh1979** [comment]
已修正
