### ISSUE TITLE
Stability issues under slow Windows machines

### ISSUE THREAD

**Issue by NetherDevil** [royqh1979/RedPanda-CPP#23]
I am writing code in a Windows VM under Ubuntu. Every time the Linux Kernel Memory Compact triggered, the RedPanda Dev-C++ in Windows VM 'crashes': It's UI was closed, but the process was still running in the background. How to solve this problem, or is it a bug?

**Comment by NetherDevil** [comment]
Btw, I think the gradual color of tab indentation mark is ugly. Can it be disabled?

**Comment by royqh1979** [comment]
I think it should be disabled by default. If not, u can turn it off anytime
in "tools"->"options"->"Editor"->"General"->"Fill Indents"

NetherDevil ***@***.***> 于2022年1月3日周一 22:07写道：

**Comment by royqh1979** [comment]
> I am writing code in a Windows VM under Ubuntu. Every time the Linux Kernel Memory Compact triggered, the RedPanda Dev-C++ in Windows VM 'crashes': It's UI was closed, but the process was still running in the background. How to solve this problem, or is it a bug?

I've never used it in a windows vm, so  I'm not sure what happened. But now you can use the Linux version, and don't need to run it in a vm under Linux.

https://github.com/royqh1979/RedPanda-CPP/releases/tag/0.12.5.linux.debian

it needs gcc g++ gdb make gdbserver libts0 installed.

**Comment by NetherDevil** [comment]
> I've never used it in a windows vm, so I'm not sure what happened. But now you can use the Linux version, and don't need to run it in a vm under Linux.
> 
> https://github.com/royqh1979/RedPanda-CPP/releases/tag/0.12.5.linux.debian
> 
> it needs gcc g++ gdb make gdbserver libts0 installed.

Thanks for your reply. I need some Windows APIs so I have to use it in the Windows VM. However, Stability in version 0.13.2 is improved and it's stable enough for me now.
