### ISSUE TITLE
编辑纯文本文件崩溃

### ISSUE THREAD

**Issue by ReverberationFromAbyss** [royqh1979/RedPanda-CPP#230]
在编辑纯文本文件时先输入英文半角括号后输入英文双引号会导致崩溃.
但是c/c++源码文件不会.
(该bug可以稳定复现, 表现如下图)
![RedPandaIDE_Qrpii0Sz3S](https://github.com/royqh1979/RedPanda-CPP/assets/133623533/e6a86bed-2a39-4ddf-912c-5666ef3fc6c3)

希望您能看见并且抽空修复该问题, 非常感谢.

**Comment by West-Pavilion** [comment]
原来如此，半个月前我在纯文本文件里编辑类似的内容也崩溃了，原来是这个原因

**Comment by royqh1979** [comment]
已修正
