### ISSUE TITLE
源代码无法通过编译

### ISSUE THREAD

**Issue by DEMONS123cell** [royqh1979/RedPanda-CPP#238]
在VS2019+MSVC2017_64上面无法通过编译：
严重性	        代码	说明	项目	文件	行	                                禁止显示状态
错误	D8021	无效的数值参数“/w44458;-Zc:rvalueCast”	RedPandaIDE	D:\QtProject\RedPanda-CPP-master (1)\RedPanda-CPP-master\RedPandaIDE\cl	1	

严重性	                        代码	说明	项目	文件	行	                                                禁止显示状态
错误(活动)	E0167	"char *" 类型的实参与 "LPWSTR" 类型的形参不兼容	redpanda-win-git-askpass	D:\QtProject\RedPanda-CPP-master (1)\RedPanda-CPP-master\tools\redpanda-win-git-askpass\main.cpp	41

**Comment by royqh1979** [comment]
fixed.
