### ISSUE TITLE
Non-free ConvertUTF.c / ConvertUTF.h

### ISSUE THREAD

**Issue by hosiet** [royqh1979/RedPanda-CPP#24]
Your project contains non-free source code files related to Unicode Inc:

* RedPandaIDE/ConvertUTF.c
* RedPandaIDE/ConvertUTF.h

You may find detailed explanation at https://lintian.debian.org/tags/license-problem-convert-utf-code .

This issue prevents your project from being packaged in Linux distributions such as Debian. Please consider fixing it by using alternative implementation like [libicu](https://icu.unicode.org/) instead.

**Comment by royqh1979** [comment]
ok. It seems that SimpleIni can use ICU instead of ConvertUTF. I'll make a
try.

Boyuan Yang ***@***.***> 于2022年1月4日周二 03:02写道：

**Comment by royqh1979** [comment]
> Your project contains non-free source code files related to Unicode Inc:
> 
>     * RedPandaIDE/ConvertUTF.c
> 
>     * RedPandaIDE/ConvertUTF.h
> 
> 
> You may find detailed explanation at https://lintian.debian.org/tags/license-problem-convert-utf-code .
> 
> This issue prevents your project from being packaged in Linux distributions such as Debian. Please consider fixing it by using alternative implementation like [libicu](https://icu.unicode.org/) instead.

These files have been removed and use libicu instead.

**Comment by hosiet** [comment]
Thanks!
