### ISSUE TITLE
如果函数的形参类型由两个及以上模板实参实例化，那么编辑器无法识别出形参的位置

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#243]
如果函数的形参类型由两个及以上模板实参实例化，那么编辑器无法识别出形参的位置

例如，给出 C++ 代码如下：

```c++
#include <iostream>

/* 两个模板形参的模板函数定义 */
template<typename T, typename E>
void two_type(std::basic_string<T, E> str, int arg)
{
	std::cout << str << " " << arg << std::endl;
}

/* 三个模板形参的模板函数定义 */
template<typename O,typename P,typename Q>
void more_type(std::basic_string<O,P,Q> mstr,int marg){
	std::cout << mstr << " " << marg << std::endl;
}

int main(){
	/* 这种情况下，编辑器将无法识别出形参的位置 */
	two_type(std::string("你好"),13);
	more_type(std::string("三个模板实参的版本"),14);
}
```

测试效果图：

![屏幕截图(259)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/6f87ac93-294b-44c6-b0d8-91ce40980b90)
如上图，可能编辑器将两个形参作为单个形参处理了

---

![屏幕截图(260)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/6b451174-e546-4107-8655-f5bbc79315bc)
在逗号处没有粗体显示形参输入位置

---

![屏幕截图(263)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/a9b57830-d138-4377-8529-2775911981d0)
标准库中的格式化函数 std::quoted

下面是对应的测试代码：

[如果函数的形参类型由两个及以上模板实参实例化，那么编辑器无法识别出形参的位置.zip](https://github.com/royqh1979/RedPanda-CPP/files/14534230/default.zip)

**Comment by royqh1979** [comment]
目前除了STL中的容器类和智能指针外，对模板的支持基本上是0
短期内也没有改进的计划
未来大概是直接走LSP上clangd
