### ISSUE TITLE
Please refactor build system to follow FHS specification (install into $prefix instead of hardcoded /opt)

### ISSUE THREAD

**Issue by hosiet** [royqh1979/RedPanda-CPP#25]
Currently the application is installed into `/opt`. This is perfectly fine for a third-party additional app, yet this is forbidden when the app intends to be part of Linux distribution. For details, please see https://lintian.debian.org/tags/dir-or-file-in-opt .

This means that the current build system needs to be refactored to [follow FHS specification and install under /usr/](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#theUsrHierarchy). The best choice is to adopt the concept of `$prefix`, which defaults to `/usr` for packaged apps and `/usr/local` for user-built programs. For more information about the concept of `$prefix`, please see https://askubuntu.com/questions/891835/what-does-prefix-do-exactly-when-used-in-configure .

I know that `qmake` has rather poor support for `$prefix`. Though migrating to `CMake` could be a good choice, there are [established rules on using `$prefix` in qmake buildsystem](https://stackoverflow.com/questions/7106442/qt-project-files-and-prefix-variable). For example, place the following snippet at the beginning of top-level `.pro` file:

```qmake
APP_NAME = RedPandaIDE

isEmpty(PREFIX) {
#    PREFIX = /opt/$${APP_NAME}/
    PREFIX = /usr/local/
}
```

When later building the project, the user can specify the detailed value for `$PREFIX`:

* `qmake PREFIX=/usr` This applies to official Linux distributions
* `qmake PREFIX=/opt/RedPandaIDE` This will install all files under /opt/ as before
* `qmake` The call without arguments will install files under `/usr/local/`.

Similarly, your files should all go into `$prefix` and adhere to current FHS specification. For example:

* `$prefix/bin/RedPandaIDE` (maps to `/usr/bin/RedPandaIDE`) for your main program
* `$prefix/libexec/RedPandaIDE/consolepauser` (maps to `/usr/libexec/RedPandaIDE/consolepauser` for your privately-used executables. If you intend to place those executables in `$PATH` so that it is system-wide visible, consider using `/usr/bin/consolepauser` instead. NOTE: please also avoid file collisions. For example, https://tracker.debian.org/pkg/astyle also provides `/usr/bin/astyle` and I am not sure if they have the same functionality.
* `$prefix/share/applications/redpandaide.desktop` (maps to `/usr/share/applications/redpandaide.desktop`) for your `.desktop` file
* `$prefix/share/RedPandaIDE/templates` (maps to `/usr/share/RedPandaIDE/templates/) for your private, architecture-independent files
* `$prefix/share/docs/RedPandaIDE/README.md` (maps to `/usr/share/docs/RedPandaIDE/README.md`) for your documentations
* `$prefix/share/pixmaps/redpandaide.png` (maps to `/usr/share/pixmaps/redpandaide.png`) for your pixmap icon

I believe this is doable with QMake, and allowing installation that does not involve with `/opt/` is also a prerequisite for entering Linux distributions. Let me know if you have any questions.

**Comment by royqh1979** [comment]
Done. Now we can use qmake PREFIX=/usr  and make install to install it to
/usr


Boyuan Yang ***@***.***> 于2022年1月5日周三 03:25写道：

**Comment by royqh1979** [comment]
The asytle included in Red-Panda C++ is a customized version

Boyuan Yang ***@***.***> 于2022年1月5日周三 03:25写道：

**Comment by hosiet** [comment]
The solution looks good. Thanks!
