### ISSUE TITLE
Functions not implemented

### ISSUE THREAD

**Issue by NetherDevil** [royqh1979/RedPanda-CPP#28]
Some functions in RedPanda-C++ has not implemented like *spliting the editor with `Control+M`* and *symbol renaming*, since they are supported in the legacy version 6.7.5.

Will these functions be implemented? If not, any alternatives?

**Comment by royqh1979** [comment]
We have spliting editor  (in the context menu of editor title bar ) and symbol renaming (in refactor menu). But i'm not sure why ctrl+M doesn't work.

**Comment by royqh1979** [comment]
Fixed in 0.14.0
