### ISSUE TITLE
no watches for global variables.

### ISSUE THREAD

**Issue by scrungy** [royqh1979/RedPanda-CPP#289]
You NEED global variables, and you need a watch for them.  only watch is locals.  This makes it very hard to debug.

**Comment by West-Pavilion** [comment]
You can use a command like `p some_global_var` in the debug console to retrieve its value.

Some major IDEs, such as CLion, operate in this manner.

**Comment by royqh1979** [comment]
> You NEED global variables, and you need a watch for them. only watch is locals. This makes it very hard to debug.

You can manually add variables (global or local) to watch in the watch panel (which is in the left part of the application window).
