### ISSUE TITLE
（概率事件）在编辑代码时使用 #include 指令，编辑器自动分析的文件数目较少

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#301]
在编辑代码时使用 #include 指令，编辑器自动分析的文件数目较少

例如，在编辑器中使用 `#include <stdlib.h>` 引入系统功能头文件，换行或保存后，可以看到编辑器界面的左下角显示 "完成3个文件的解析"，此时输入 malloc ，编辑器不会显示该函数的补全提示。

如果退出后重新打开该文件，就会看到编辑器界面的左下角显示 "完成25个文件的解析"，此时输入 malloc 等函数，编辑器会显示这些函数的补全提示。

此现象的出现是具有概率性的，有可能第一次尝试就会出现，也有可能多次不出现，换一个文件尝试就会出现。

示例视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/44b22a4f-ff4c-4248-b068-e6db45462a48

暂时还没发现具体触发该现象的机制，因而没有测试代码

**Comment by Ltabsyy** [comment]
也许，这其实就是#304
