### ISSUE TITLE
引入 cstdio 头文件时，需要使用 Ctrl + 鼠标左键 进入一次 cstdio，编辑器才能识别出 std::printf 等为函数类型

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#303]
引入 cstdio 头文件时，需要使用 Ctrl + 鼠标左键 进入一次 cstdio，编辑器才能识别出 std::printf 等为函数类型

该 issue 的具体原因将在下一条 issue 中分析，此 issue 只做现象记录

下面是示例视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/92cf24e0-1c75-400a-8c7b-b7a32f2c070c

测试代码将在下一条 issue 中给出

**Comment by royqh1979** [comment]
在生成补全列表/语法高亮时，如果将每个using alias都展开成对应的实际定义，会消耗相应的处理时间；在低配机器上可能会造成卡顿。

而不展开对实际使用也没有大的影响。

因此暂不考虑修改。
