### ISSUE TITLE
小熊猫C++的编辑器在分析头文件时的 "惰性机制"

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#304]
小熊猫C++的编辑器在分析头文件时的 "惰性机制"

在源文件中包含如 `cstdio`，C++ 的 `stdlib.h` 等需要分析多重依赖的头文件时发现的特性。即在包含上述头文件时，如果在之前的使用中，编辑器已经分析了另一个文件中较多的头文件时，那么编辑器会只分析较少的头文件。

复现方法：

1. 打开一个会促使编辑器分析较多头文件的源代码文件
2. 新建一个 C++源代码文件并打开，或者打开一个已经存在的源代码文件
3. 在第 2 步中选择的新文件中，引入 `cstdio` 或 `stdlib.h` 头文件
4. 此时，会发现编辑器只会分析较少的文件，即分析不完全

下面是示例视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/28f1cd66-365c-4897-9e70-4d80b851c47d

由于此 "惰性机制" 的存在，小熊猫C++ 在同时编辑多个文件时，可能会出现编辑器的智能补全提示表现不稳定的情况。

下面是对应的测试代码文件夹：

[小熊猫C++的编辑器在分析头文件时的 '惰性机制'.zip](https://github.com/royqh1979/RedPanda-CPP/files/14730107/C%2B%2B.zip)

**Comment by royqh1979** [comment]
bits/stdc++.h完全解析后会占用100M+内存。为了保证在内存较少的机器上也能打开多个文件，小熊猫C++默认所有编辑器共用一个代码分析器。

对于内存较大、代码分析准确性要求高的用户，可以在选项->环境->性能中关闭“编辑器共享同一个代码分析器”。
