### ISSUE TITLE
输入 const，volatile，constexpr，constveal，constinit 后，编辑器不显示 static 和 extern 的补全提示，反之亦然

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#305]
输入 const，volatile，constexpr，constveal，constinit 后，编辑器不显示 static 和 extern 的补全提示，反之亦然

在 C++ 中，可以使用 `constexpr static int CONSTANT = 8888` 这样的方式定义一个常量。然而，在当前版本的编辑器中，输入了 constexpr 后，再输入 static 是没有补全提示的。反之，先输入 static，再输入 constexpr 也是没有补全提示的。

![屏幕截图(295)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/d0dd574e-2a70-429a-a498-c6d6f8944679)

下面是对应的测试代码：

[输入 const，volatile，constexpr，constveal，constinit 后，编辑器不显示 static 和 extern 的补全提示，反之亦然.zip](https://github.com/royqh1979/RedPanda-CPP/files/14730566/const.volatile.constexpr.constveal.constinit.static.extern.zip)

**Comment by Mc-GrowlR** [comment]
我测试的情况中，在函数参数列表中输入`const`后，不出现补全列表
