### ISSUE TITLE
在多行注释的第二行及之后的行中输入 Ctrl + 回车键，会导致注释内容分行

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#306]
在多行注释的第二行及之后的行中输入 Ctrl + 回车键，会导致注释内容分行

演示视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/60f0da85-843f-48e1-9a53-698fe94610b5

下面是对应的测试代码：

[在多行注释的第二行及之后的行中输入 Ctrl + 回车键，会导致注释内容分行.zip](https://github.com/royqh1979/RedPanda-CPP/files/14730595/Ctrl.%2B.zip)

**Comment by royqh1979** [comment]
设计即如此。在/* */中断行不会自动插入行首*
