### ISSUE TITLE
如果光标停留在编辑器视图中，那么程序的焦点无法正确聚焦到其他视图中

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#310]
在调试面板的局部变量、断点、调用栈、内存视图上 按 Ctrl + C 复制时，复制的是编辑器界面中的内容，程序的焦点无法聚焦在调试面板上

在文件面板、项目面板、监视面板、结构面板、试题集面板、底部的编译器面板、工具输出面板、查找面板、TODO面板、书签面板、试题面板上，也无法正确自动聚焦，选中内容后复制的仍是编辑器界面中的内容

在最新版本的 小熊猫C++ 中，无法将程序的焦点聚集在 调试主控台 中的现象又出现了

现在在 调试主控台 中使用快捷键 Ctrl + C 、Ctrl + V 进行复制和粘贴内容时，无法产生相应的效果，需要使用鼠标右键调出上下文菜单，才能使用快捷键 Ctrl + C 和 Ctrl + V 进行复制和粘贴内容

演示视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/bdf5ad27-ca4e-4b85-a46d-638f89625afc

下面是对应的测试代码：

[在调试面板的局部变量、断点、调用栈上按 Ctrl + C 复制时，复制的是编辑器界面中的内容，程序的焦点无法聚焦在调试面板上.zip](https://github.com/royqh1979/RedPanda-CPP/files/14730910/Ctrl.%2B.C.zip)

**Comment by royqh1979** [comment]
Qt的主菜单项全局快捷键永远优先于子控件快捷键。

不知道有什么好办法来解决这个问题
