### ISSUE TITLE
在范围 for 循环中使用的变量会出现在后续的作用域中

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#315]
在范围 for 循环中使用的变量会出现在后续的作用域中

C++11 引入了一种新的 基于范围的 for 循环，它在用于数组和容器遍历时，是相较于 传统 for 循环 的更加简洁可读的等价版本

然而，在当前版本的编辑器中使用 基于范围的 for 循环，会发现在循环遍历中使用的变量名会出现在循环结束后的作用域中

请考虑如下的 C++ 代码：

```cpp
#include <iostream>
#include <vector>

/* 在范围 for 循环中使用的变量会出现在后续的作用域中 */

int main(){
	std::vector fib{1,1,2,3,5,8,13,21,34};
	/* 这里使用 范围 for 循环 遍历 fib*/
	for(auto elem_fib : fib){
		std::cout << elem_fib << " ";
	}
	/* 在这里输入 elem ,会发现编辑器会显示已经离开作用域的变量 elem_fib */
//	ele
//	std::cout << elem_fib << std::endl;
}
```

实际效果演示图：

![屏幕截图(306)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/3a5897dc-e316-453c-89d2-e7e3af51f375)

下面是对应的测试代码：

[在范围 for 循环中使用的变量会出现在后续的作用域中.zip](https://github.com/royqh1979/RedPanda-CPP/files/14734264/for.zip)

**Comment by Ltabsyy** [comment]
更局部的作用域，作用域的前后范围，这不有很多问题？现在看来不急也没必要解决

**Comment by West-Pavilion** [comment]
> 更局部的作用域，作用域的前后范围，这不有很多问题？现在看来不急也没必要解决

是的，但是我发现这个特性会让接下来的普通变量的判定失效，即如果存在 范围 for 循环 的用法，其它的普通变量可能也无法被编辑器正确处理了
