### ISSUE TITLE
Not reusing windows(opening a new tab instead of a new window) when opening file with an existing window

### ISSUE THREAD

**Issue by 00001H** [royqh1979/RedPanda-CPP#32]
If a window is already open, opening another file(via double-click in File Explorer) will open up a new window, instead of a new tab. This is a great inconvenience because it makes it more tedious to switch between files. Considering it already supports multi-tabbing, this should be pretty easy to do.(Note: Orwell Dev-C++ *does* reuse windows(and support multi-tabbing)).

Note: Using File -> open opens a new tab in the same window, and so does dragging&dropping a file into the window.

Maybe you are having a problem of communicating between the newly launched process for opening a file and the already-open window?

Chinese version:(I am actually Chinese so this isn't translated using a translator)
即使已经有打开的窗口了，双击文件还是会打开新窗口，而不是在已有的窗口里打开一个标签页。这样很不方便，因为切换文件变得更麻烦了。Red Panda Dev-C++已经支持多标签页了，所以这应该不难实现。（注：Orwell Dev-C++*会*重用窗口，可以参考一下Orwell的代码）

使用`文件->打开`菜单项，或拖拽文件进编辑器窗口会打开新标签页，而不是新窗口。

可能你们不能让为打开新文件启动的进程通知已有的窗口添加标签页？

**Comment by royqh1979** [comment]
可以使用小熊猫C++左侧边栏的文件视图来打开多个文件。或者使用拖拽来打开多个文件。

没有像orwell（和小熊猫Dev-C++ 6.7）一样做成在同一个进程中打开，是因为在一些场景下，需要同时打开两个或者进程方便调试（比如写TCP/IP Client/Server通信程序）

**Comment by 00001H** [comment]
> 是因为在一些场景下，需要同时打开两个或者进程方便调试（比如写TCP/IP Client/Server通信程序）
可以加一个右键菜单项？
