### ISSUE TITLE
建议给试题的测试样例输入界面加一个保存按钮和快捷键

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#324]
建议给试题的测试样例输入界面加一个保存按钮和快捷键

在自定义测试样例的输入和期望输出时，如果不对其进行保存，有可能会丢失输入的数据。

建议加一个手动保存的按钮和快捷键，确保自定义的测试样例能够被保存下来.

会导致自定义的测试样例丢失的情况的演示视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/9a2c87a1-1d30-4eb7-9ff1-63e37a00490c

**Comment by royqh1979** [comment]
在试题集面板中有保存按钮

**Comment by West-Pavilion** [comment]
> 在试题集面板中有保存按钮

好吧，确实如此，但是我觉得在切换试题的时候，正在编辑的测试样例不会自动保存挺不方便的
