### ISSUE TITLE
新建一个jackpot项目出错

### ISSUE THREAD

**Issue by lelandyang** [royqh1979/RedPanda-CPP#33]
当我尝试新建一个JackPot项目时，main.c显示的是“Jackpot_c.txt”这个文件名，而不是该模板文件里面的代码。
截图如下所示：
![image](https://user-images.githubusercontent.com/10257460/154976199-7cc5fc32-e113-421b-be4f-6980be770fbe.png)

**Comment by royqh1979** [comment]
嗯，这个模板有问题

**Comment by royqh1979** [comment]
fixed
