### ISSUE TITLE
Gutter Active Line doesn't follow the cursor.

### ISSUE THREAD

**Issue by NetherDevil** [royqh1979/RedPanda-CPP#36]
Type sonething in the editor, and then position the cursor with mouse to the end of a line. The Active Line followed the cursor, but the Gutter Active Line doesn't.

![ORD(N(O15YP0XIPIN%O1KRA](https://user-images.githubusercontent.com/80260541/159110275-4072a146-dcca-4423-ae93-f594ba910596.png)

The cursor is at the end of the Line 4.

**Comment by royqh1979** [comment]
fixed
