### ISSUE TITLE
小熊猫3.0RC1对于大文件(>50M)且单行字符数较多的文件，在快速拖动竖向滚动条时间歇性卡顿

### ISSUE THREAD

**Issue by xccfcpd** [royqh1979/RedPanda-CPP#366]
**小熊猫3.0RC1对于大文件(>50M)且单行字符数较多的文件，在快速拖动竖向滚动条时间歇性卡顿**

**如视频所示**

https://github.com/royqh1979/RedPanda-CPP/assets/157192220/8a0e6137-4646-473a-8460-07efb46d817a

因为视频展示文件较大，因此放置于百度盘。链接: https://pan.baidu.com/s/17R5ugEssRTe7C_t-DHd49A?pwd=wh9s 提取码: wh9s 请老师验证下，看看能否修复下(用v2.26对比，无此卡顿现象)。

**Comment by royqh1979** [comment]
小熊猫C++的本意是代码编辑器。正常情况下每行字符个数不会超过1000个；你这个文件单行字符超过180万个，卡就卡吧。

**Comment by Ltabsyy** [comment]
额，2.26在300行左右慢速滚动也是卡的，其中249行有632718列，你这文件本身就不会流畅

**Comment by xccfcpd** [comment]
遇到极端的特例了，小熊猫已经很好了。
