### ISSUE TITLE
建议工具配置页添加 “当前编辑器中所选内容” 宏指令

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#367]
建议工具配置页添加 “当前编辑器中所选内容” 宏指令

在当前版本的 小熊猫C++ 中，外部工具与当前编辑器中的内容交互的可选宏指令只有 “当前编辑器中光标处的单词” 这一个选项

如果能够将当前编辑器中所选的内容传递给外部工具进行处理，那么在 小熊猫C++ 中定制自己喜欢的小工具将会变得非常方便

因此，建议在工具配置页中添加 “当前编辑器中所选内容” 宏指令

![屏幕截图(337)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/56060739-6c9e-4f1d-9c1a-62d5885bbd2d)

**Comment by royqh1979** [comment]
请看“重定向输入”下拉框
