### ISSUE TITLE
编辑器认为标准库头文件有错误

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#368]
编辑器认为标准库头文件有错误

在查看标准库头文件的内容时，发现编辑器提示它有错误。

![屏幕截图(338)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/d18bddcc-fe2f-4074-8088-481619552624)

出现这种情况的头文件都是在二级文件夹的目录中，可能是编辑器认为其不是标准库头文件，因为这种二级文件夹中的头文件不是只读的，而其它标准库头文件都是只读的。

![屏幕截图(339)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/995a6198-379b-4506-986a-581ef4770f38)

下面是对应的测试代码：

[编辑器认为标准库头文件有错误.zip](https://github.com/royqh1979/RedPanda-CPP/files/14852074/default.zip)

**Comment by royqh1979** [comment]
这个得问为什么gcc认为它有错误
