### ISSUE TITLE
Translation into other languages!

### ISSUE THREAD

**Issue by arbarbosa1979** [royqh1979/RedPanda-CPP#37]
Is it possible to translate your program beyond the two available languages, which files would need to be changed to achieve this?

**Comment by royqh1979** [comment]
Sure it's possible. 

If you'd like to do the translation, I can generate a .ts file for your language, then you can use Qt Liguist to do the translation.

**Comment by arbarbosa1979** [comment]
> Sure it's possible.
> 
> If you'd like to do the translation, I can generate a .ts file for your language, then you can use Qt Liguist to do the translation.

I would be very grateful if you could do that, I tried to find a way to translate it, but as I didn't succeed I decided to open this request. My native language is Portuguese, so it is easier for me to translate from English, as my knowledge of Asian languages is limited.

**Comment by royqh1979** [comment]
I have add the Portuguese language file "RedPandaC++/RedPandaIDE_pt.ts" to the project. You can use qt linguist to open and translate it.

When you finish, just make a PR and I'll merge it.

**Comment by arbarbosa1979** [comment]
Thanks, when I'm done I'll do a PR.
