### ISSUE TITLE
莫名奇妙群被踢了

### ISSUE THREAD

**Issue by paditianxiu** [royqh1979/RedPanda-CPP#372]
![Screenshot_2024-04-06-04-34-25-282_com tencent mobileqq](https://github.com/royqh1979/RedPanda-CPP/assets/77879960/0acb2330-33f7-44b6-83b2-9cb584cad479)
QQ3373587110

**Comment by royqh1979** [comment]
说啥了？聊天记录里看不到了

**Comment by paditianxiu** [comment]
啥都没说啊，就发了一个表情一个表情包



---原始邮件---
发件人: "Roy ***@***.***&gt;
发送时间: 2024年4月6日(周六) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [royqh1979/RedPanda-CPP] 莫名奇妙群被踢了 (Issue #372)




 
说啥了？聊天记录里看不到了
