### ISSUE TITLE
在编辑器中使用 Ctrl + 鼠标左键 无法通过 using ::system 语句跳转到对应的函数原型声明（该现象仅在GCC中发生）

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#373]
在编辑器中使用 Ctrl + 鼠标左键 无法通过 using::system 语句跳转到对应的函数原型声明（该现象仅在GCC中发生）

以 GCC 的 std::system 为例，编辑器能够找到 using ::system 语句，但无法通过它跳转到对应的函数原型声明

演示视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/74f581b5-6c51-4914-aa40-c4ef7ba78088

而 Clang 的 std::system 能够通过使用 Ctrl + 鼠标左键 的方式跳转到对应的函数原型声明

下面是对应的测试代码：

[在编辑器中使用 Ctrl + 鼠标左键 无法通过 using;;system 语句跳转到对应的函数原型声明.zip](https://github.com/royqh1979/RedPanda-CPP/files/14892804/Ctrl.%2B.using.system.zip)

**Comment by royqh1979** [comment]
把选项里的环境->性能页里的“编辑器共享同一个代码分析器”关掉。

**Comment by West-Pavilion** [comment]
已通过取消勾选 “编辑器共享同一个代码分析器” 选项解决，即将关闭此 issue
