### ISSUE TITLE
编辑txt崩溃

### ISSUE THREAD

**Issue by UndefinedCpp** [royqh1979/RedPanda-CPP#38]
编辑txt文件时输入左括号```(```导致崩溃，但```[```则不会。另外，建议加入对其他种类文件（比如markdown）的高亮显示。

**Comment by NetherDevil** [comment]
> Enter the opening parenthesis when editing the txt file `(` causes a crash, but `[` then doesn't..

Not exactly. The editor crashs only when a bracket is typed at the beginning of a line while editing non-code files, and typing at the beginning of the first line does't trigger the crash.

And for Markdown preview, I think you should use something like Visual Studio Code or Typora, but not RedPanda C++.

**Comment by NetherDevil** [comment]
>Enter the opening parenthesis when editing the txt file `(` causes a crash, but `[` then doesn't..

Not exactly. The editor crashs only when a bracket is typed at the beginning of a line while editing non-code files, and typing at the beginning of the first line does't trigger the crash. Not only parenthesis (`()`) can trigger the crash, square brackets (`[]`) triggers that as well, so do braces (`{}`) and angle brackets (`<>`).

And for Markdown preview, I think you should use something like Visual Studio Code or Typora, but not RedPanda C++.

**Comment by royqh1979** [comment]
fixed
