### ISSUE TITLE
Incorrectly parsed or assigned tokens in exported HTML file.

### ISSUE THREAD

**Issue by NetherDevil** [royqh1979/RedPanda-CPP#39]
1. Namespaces are assigned class `syncpphighlighter0-string` in exported HTML files.
2. Header files are parsed as other things like classes, symbols etc.
![image](https://user-images.githubusercontent.com/80260541/161744041-df424d24-d7c9-4135-9425-6a7a15e11ba3.png)

**Comment by royqh1979** [comment]
We don't have the item "namespace" in the color scheme, so namespaces is highlighted with "string"'s color scheme settings

**Comment by NetherDevil** [comment]
> We don't have the item "namespace" in the color scheme, so namespaces is highlighted with "string"'s color scheme settings

But why the header files are highlighted with "class" and "variable"?

**Comment by NetherDevil** [comment]
btw, the keyword `override` is not highlighted.

**Comment by royqh1979** [comment]
because override is not a keyword...
You can try to use "override" as a variable name, and it can be compiled.

NetherDevil ***@***.***> 于2022年4月6日周三 10:46写道：

**Comment by NetherDevil** [comment]
But I do not understand why the names of the header file is highlighted with "class" and "variable", which differs from the behavior in the IDE.

**Comment by NetherDevil** [comment]
Expected behavior or a bug?

**Comment by royqh1979** [comment]
Because  reuse existing color scheme settings is not harmful, and I don't
want to add 2 color scheme settings for "local headers" and "system
headers" and modify all predefined color schemes, which means lots of work.


NetherDevil ***@***.***> 于2022年4月6日周三 09:53写道：

**Comment by NetherDevil** [comment]
Oh, thanks. In fact I've completely forgotten this issue. Now I export the HTML code directly from Visual Studio Code. Thanks for responding anyway.
