### ISSUE TITLE
编辑器的自动缩进对 switch 语句中的标签的缩进计算不正确

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#398]
编辑器的自动缩进对 switch 语句中的标签的缩进计算不正确

如果在 switch 语句中输入 case 标签，那么在输入冒号 ':' 的瞬间，编辑器会对该标签减少一级缩进，这时必须手动使用 Ctrl + Shift + A 进行代码格式化来保持代码缩进的统一

同时，编辑器的自动缩进功能与代码模板中的 switch 模板也有冲突

演示视频：

https://github.com/royqh1979/RedPanda-CPP/assets/111393157/699aade6-d633-4120-9663-0a5bae214d71

下面是对应的测试代码：

[编辑器的自动缩进对 switch 语句中的 case 标签的缩进计算不正确.zip](https://github.com/royqh1979/RedPanda-CPP/files/15131477/switch.case.zip)

**Comment by royqh1979** [comment]
我喜欢case与switch对齐。

**Comment by West-Pavilion** [comment]
好的。用户可以通过手动取消勾选 工具->选项->代码排版->通用->缩进2->缩进switch语句 来获得统一的缩进排版
