### ISSUE TITLE
当 #include 后的内容是宏定义时，编辑器无法找到其包含的头文件的内容

### ISSUE THREAD

**Issue by West-Pavilion** [royqh1979/RedPanda-CPP#407]
当 #include 后的内容是宏定义时，编辑器无法找到其包含的头文件的内容

例如，请考虑如下的 C++ 代码：

```cpp
#define CPP_BASIC_IO <iostream>

/* 当 #include 后的内容是宏定义时，编辑器无法找到其包含的头文件的内容 */

#include CPP_BASIC_IO

int main(){
	/* 通过这种方式包含的头文件 <iostream> 里的函数可以正常调用 */
	std::cout << "header is included by macro" << std::endl;
}
```

在小熊猫C++（rc2版 3.0.2750）中，这种使用宏定义来指定 #include 的头文件名的用法尚未被编辑器的智能补全提示支持

这种用法是在 raylib 的 c++ wrapper 库中发现的：https://github.com/RobLoach/raylib-cpp

![屏幕截图(381)](https://github.com/royqh1979/RedPanda-CPP/assets/111393157/48057cd2-f95e-4d18-ba03-6b30333d3c3f)

下面是对应的测试代码：

[当 #include 后的内容是宏定义时，编辑器无法找到其包含的头文件的内容.zip](https://github.com/royqh1979/RedPanda-CPP/files/15159549/include.zip)

**Comment by royqh1979** [comment]
真刑

**Comment by Ltabsyy** [comment]
不愧是West-Pavilion
