### ISSUE TITLE
Weird Crash for a particular piece of code.

### ISSUE THREAD

**Issue by aenlemmea** [royqh1979/RedPanda-CPP#412]
```cpp
#include <map>
#include <set>
#include <list>
#include <cmath>
#include <deque>
#include <queue>
#include <stack>
#include <string>
#include <bitset>
#include <cstdio>
#include <limits>
#include <vector>
#include <climits>
#include <cstring>
#include <cstdlib>
#include <numeric>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <unordered_map>

#define all(x) (x).begin(), (x).end()
#define arr_all(x, y) x, x + y
#define F(i, start, n) for (auto i = start-(start > n); (i < n)^(start > n); i += 1-2*(start > n))
#define done return;
#define puni(x) int x; cin >> x;

#define fin "\n"

using namespace std;

void solve() {
	pair<int, int> A, B, F;
	cin >> A.first >> A.second;
	cin >> B.first >> B.second;
	cin >> F.first >> F.second;
	
	int ans = abs(A.first - B.first) + abs(A.second - B.second);
}

int main() {
	
	ios_base::sync_with_stdio(false);
	cin.tie(0);
	cout.tie(0);
	
	int t;
	cin >> t;
	while (t--) {
		solve();
	}
	return 0;
}
```

If I try to add the line `if (A.first == F. ...` after `int ans = ...` then the IDE instantly crashes. It seems like something regarding showing command completions for F is failing. Just doing `F.` itself crashes RPCPP.

I am on Windows. Portable edition. Version: 2.26.2249 (x86_64)

**Comment by Ltabsyy** [comment]
这个在最新版已经修复了，等2.27/3.0正式版即可。
This has been fixed in the latest version, wait for the official version of 2.27/3.0.

**Comment by aenlemmea** [comment]
> 这个在最新版已经修复了，等2.27/3.0正式版即可。 This has been fixed in the latest version, wait for the official version of 2.27/3.0.

Can I get a CI artifact for local use? The software is crashing a lot for the command completion. Recently I lost all progress in a few files.
我可以获得 CI 工件供本地使用吗？该软件在完成命令时经常崩溃。最近我丢失了一些文件的所有进度。

**Comment by aenlemmea** [comment]
Can I get an early CI artifact build because the crashes are happening too often now. I lost a few files completely due to this bug.


我能否获得早期的 CI 工件构建，因为现在崩溃发生得太频繁了。由于这个错误，我完全丢失了一些文件。

**Comment by royqh1979** [comment]
https://github.com/royqh1979/RedPanda-CPP/actions

> Can I get an early CI artifact build because the crashes are happening too often now. I lost a few files completely due to this bug.
> 
> 我能否获得早期的 CI 工件构建，因为现在崩溃发生得太频繁了。由于这个错误，我完全丢失了一些文件。

You can get the newest build from https://github.com/royqh1979/RedPanda-CPP/actions

**Comment by aenlemmea** [comment]
I did search there but couldn't find a link to any exe. I will look again I
guess.

**Comment by royqh1979** [comment]
> I did search there but couldn't find a link to any exe. I will look again I guess.

You can click into the “build” workflow，then click into the latest finished workflow run.
Scroll down to the bottom the page, you'll find the artifacts.
