### ISSUE TITLE
希望编译器设置选项中增加只生成预编译代码(-E)的选项, 以便于学习和调试宏代码

### ISSUE THREAD

**Issue by hlizard** [royqh1979/RedPanda-CPP#42]
希望编译器设置选项中增加只生成预编译代码(-E)的选项, 以便于学习和调试宏代码, 设置项的位置可放在当前"只生成汇编代码(-S)"选项所在的"输出"tab页.

**Comment by royqh1979** [comment]
增加编译选项会导致配置文件和旧版本不兼容，所以近期暂时不考虑增加。

有时间了需要重新设计配置文件的格式。

**Comment by hlizard** [comment]
Red Panda C++ Version 1.0.8

    enhancement: auto complete '#undef'
    enhancement: redesign components for compiler commandline arguments processing
    fix: selection calculation error when editing in column mode
    enhancement: add compiler commandline argument for "-E" (only preprocessing)
    enhancement: auto set output suffix to ".expanded.cpp" when compiler commandline argument for "-E" is turned on
    enhancement: auto set output suffix to ".s" when compiler commandline argument for "-S" is turned on
    enhancement: show error message when user set a shortcut that's already being used.
    enhancement: adjust scheme colors for "dark" and "high contrast" themes
    enhancement: can debug files that has non-ascii chars in its path and is compiled by clang
    fix: when debugging project, default compiler set is wrongly used


谢谢!
