### ISSUE TITLE
断点、活动断点若仅设置前景色，不设置背景色，前景色不会生效

### ISSUE THREAD

**Issue by Ltabsyy** [royqh1979/RedPanda-CPP#441]
![屏幕截图 2024-05-29 125427](https://github.com/royqh1979/RedPanda-CPP/assets/111294086/f0c0aed6-e3b0-4631-9b78-93d9c57666ef)

**Comment by royqh1979** [comment]
只改前景色不改背景色没有太大意义。
没必要改
