### ISSUE TITLE
建议增加clang-format支持

### ISSUE THREAD

**Issue by muqian2022** [royqh1979/RedPanda-CPP#446]
算是一点私心吧，希望作者可以支持`Clang Format`格式化，因为`Clang Format`可以通过`.clang-format`文件对代码进行格式化，这样可以让我在其他软件上的代码格式在RED PANDA上也可以完美复现出来，而不用自己去调整代码格式。(✿◕‿◕✿)

**Comment by royqh1979** [comment]
在选项->工具里自己配吧。

**Comment by CrystalLiquid** [comment]
不是已经支持自定义命令了吗。。

**Comment by muqian2022** [comment]
> 不是已经支持自定义命令了吗。。

最近才下回来了的，不了解更新的功能，文档也没搜到clang format相关内容，所以以为小熊猫C++没有支持。能麻烦教教怎么弄吗？作者回复我了，我尝试了，但还是不会搞，也不想去麻烦作者。

**Comment by muqian2022** [comment]
> 不是已经支持自定义命令了吗。。

![屏幕截图 2024-06-10 205623](https://github.com/royqh1979/RedPanda-CPP/assets/97910545/d70b06e4-5b17-4ae1-a3c3-21ec05794678)
之前我尝试搞了一下，就是有这个问题，`clang-format.exe`加`-i`参数，每次调用clang format会提示我文件被修改是否重新加载，很麻烦，如果不加`-i`参数，把输出内容直接写入文档，就会出现如图问题，程序把调用命令也写上了，有点不明白，是小熊猫的bug还是我哪里操作不对

**Comment by muqian2022** [comment]
> > > 不是已经支持自定义命令了吗。。
> > 
> > 
> > 之前我尝试搞了一下，就是有这个问题，`clang-format.exe`加`-i`参数，每次调用clang format会提示我文件被修改是否重新加载，很麻烦，如果不加`-i`参数，把输出内容直接写入文档，就会出现如图问题，程序把调用命令也写上了，有点不明白，是小熊猫的bug还是我哪里操作不对
> 
> 在工具设置中： （1）不要在”参数“中指定文件名 （2）将“重定向输入”设为“当前文件内容” （3）将“输出到”设为“替换整个文档” （4）勾选”使用UTF8“编码

我是按照这个要求来的

![image](https://github.com/royqh1979/RedPanda-CPP/assets/97910545/ac549250-863e-4af4-86c7-606f7ee634cc)

但是，有这个问题，这是我在调用时候被自动加上的，和我上次遇到的情况一样。感觉这可能是个bug吧

![屏幕截图 2024-06-11 191234](https://github.com/royqh1979/RedPanda-CPP/assets/97910545/af8225d6-ca25-4ad2-be65-64ccb7e3a883)

**Comment by royqh1979** [comment]
> 我是按照这个要求来的
“程序”里填clang-format的完整路径

**Comment by muqian2022** [comment]
> > 我是按照这个要求来的
> 
> “程序”里填clang-format的完整路径

可以了，感谢
