### ISSUE TITLE
浅论配色开发中一些不合理的弹窗

### ISSUE THREAD

**Issue by Ltabsyy** [royqh1979/RedPanda-CPP#447]
经过目前的bug修复，3.1的配色开发体验已然比3.0强得多，然而还没有真正完善，长期以来都会遇到一些不合理的弹窗，经长期实践，可归纳为以下3条：
(1)更改配色编辑器左侧元素选择栏定位位置，即认为存在修改。
此时切换到其他页提示保存修改，“应用”也会亮起。
(2)修改后直接删除自定义修改的原装配色，应用会报错。
必须修改后“确认”，重新进入后删除，“应用”后删除仍然报错。
非原装配色不存在此问题。
(3)通过文件管理器手动导入的、空格为空格而非下划线的配色文件，不能被删除。
（通过文件管理器粘贴，重启小熊猫即可正常导入，这是一种批量导入方法）
（考虑到内存修改对软件来说并非常规行为，此条可无视）

当然，目前版本(2858)已经够用了，但如果能对以上问题浅作考虑，那必然更优。

**Comment by CrystalLiquid** [comment]
其实能把include file也加入解析我觉得就已经是能用了

**Comment by CrystalLiquid** [comment]
其实能把include file也加入解析我觉得就已经是很好用了

**Comment by Ltabsyy** [comment]
将关闭此issue，在3.1正式版的基础上重新整理并分开表述
