### ISSUE TITLE
有什么办法能在项目管理栏中默认显示子目录名称吗

### ISSUE THREAD

**Issue by sdkljd** [royqh1979/RedPanda-CPP#466]
![捕获](https://github.com/royqh1979/RedPanda-CPP/assets/116957851/46ef4ff3-d9f9-4998-b1fc-ea800a8f4e47)
如图，每次打开项目后都得在项目管理栏中右键 切换为自定义视图 然后在切换为普通视图 才能显示项目文件夹中的子目录

**Comment by royqh1979** [comment]
直接点文件夹左侧的箭头不能展开？

**Comment by sdkljd** [comment]
> 直接点文件夹左侧的箭头不能展开？
![捕获](https://github.com/royqh1979/RedPanda-CPP/assets/116957851/2f98c4da-3e5e-46c1-8db5-4c41fc6d40d2)
默认情况是这样的，而需要的话就得在 项目管理栏中右键 切换为自定义视图 然后在切换为普通视图
