### ISSUE TITLE
3.2 alpha: Inconvenient backslash and quotation mark behaviour

### ISSUE THREAD

**Issue by Oscillograph** [royqh1979/RedPanda-CPP#485]
Hello!

In the recent IDE build there's an inconvenient behaviour of color schemes. Here's a gif animation to illustrate it:

![001-008](https://github.com/user-attachments/assets/b32085cc-7f1e-4eb2-8d99-d406b5b8b727)

If a backslash is added right before a quotation mark, the latter is considered to be turned into a regular string character (which is good), but it doesn't visually turn back to special character by itself if other symbols are typed after the backslash -- workarounds like "backslashing a backslash and removing the extra one" should be applied to make it happen.

**Comment by royqh1979** [comment]
Sorry but I didn't understand what you mean from the gif.

Can you give a demo and describe it step by step?

**Comment by Ltabsyy** [comment]
这就比如我要在这输入\n
![image](https://github.com/user-attachments/assets/6733d7cc-38bd-4a7f-a3d3-d91549aa97d9)
输入\之后，输入n之前，后面的内容都会以字符串识别
![image](https://github.com/user-attachments/assets/93f4263e-868f-49a0-bf5c-79276e6e3a53)
这其实没什么，但在输入n之后，后面的内容可能不会恢复成以前的状态，这是不正常的
![image](https://github.com/user-attachments/assets/7fcfa58c-ca63-44a7-a141-7c1ad8e64e7c)

**Comment by royqh1979** [comment]
3.2.2280里还能重现这个问题吗？我试不出来

> 这就比如我要在这输入\n ![image](https://private-user-images.githubusercontent.com/111294086/367140090-6733d7cc-38bd-4a7f-a3d3-d91549aa97d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ1MTEsIm5iZiI6MTcyNjY0NDIxMSwicGF0aCI6Ii8xMTEyOTQwODYvMzY3MTQwMDkwLTY3MzNkN2NjLTM4YmQtNGE3Zi1hM2QzLWQ5MTU0OWFhOTdkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGQ3NThiOTdkZTIxNTBjMjM3MmE0MDZiZWVmOTI2NzA4NWY3MGU0NTg2M2NkMjgyMTI4YWZkZTNlNzEzNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jH10s_5CD61z9B61G6qun_QSl_SKO1jnOWWApMXvnpM) 输入\之后，输入n之前，后面的内容都会以字符串识别 ![image](https://private-user-images.githubusercontent.com/111294086/367140234-93f4263e-868f-49a0-bf5c-79276e6e3a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ1MTEsIm5iZiI6MTcyNjY0NDIxMSwicGF0aCI6Ii8xMTEyOTQwODYvMzY3MTQwMjM0LTkzZjQyNjNlLTg2OGYtNDlhMC1iZjVjLTc5Mjc2ZTZlM2E1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmE5ODI5MGE4ZjY2Nzk0MDM2YTk1NDkwYmFhNDJmNzViOWE2YTFjYjhhYmNhZjI0N2I3MmVhY2Q1MWVkYzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FTHR3bxsZKXyrsZl8uC3T41LFshP00_n30KT8ZHz4Xk) 这其实没什么，但在输入n之后，后面的内容可能不会恢复成以前的状态，这是不正常的 ![image](https://private-user-images.githubusercontent.com/111294086/367140386-7fcfa58c-ca63-44a7-a141-7c1ad8e64e7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ1MTEsIm5iZiI6MTcyNjY0NDIxMSwicGF0aCI6Ii8xMTEyOTQwODYvMzY3MTQwMzg2LTdmY2ZhNThjLWNhNjMtNDRhNy1hMTQxLTdjMWFkOGU2NGU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzIzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2MyZjhlMzU1ZDQ4OWM2ZGQwOTk3ODY3MjRmZjBlYWM2NTc2NDg5NGIwNzRmMzNlMDczODRkMzUxY2NkMjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GMLUMMK_IBE_yeWE82wzIIunp3ttJ21w1al8z2iBJNk)

**Comment by Ltabsyy** [comment]
```
2024/9/6 15:53:49 3.2.2880
修正：bits/c++不能自动以只读模式打开
修正：选项/编辑器/配色中的编译器示例中，光标未定位在第一行
```
没有
```
2024/9/11 15:35:25 3.2.2883
修正：变量初始化（）或{}后未跟逗号或分号时可能引起闪退
```
没有
```
2024/9/12 11:02:24 3.2.2883
修正：粘贴/替换大块内容时速度过慢
```
没有
```
2024/9/12 12:19:36 3.2.2883
修正：未merge昨天的修改
```
有
```
2024/9/13 19:06:05 3.2.2891
修正win7 crash bug(by cynao.CN)
变换：先按住ctrl然后拖拽鼠标也可以开始拖拽内容
```
有
