### ISSUE TITLE
[feat] 想要Microsoft式代码排版

### ISSUE THREAD

**Issue by LY-Xiang** [royqh1979/RedPanda-CPP#487]
由于习惯用**vs/vsc**,
在为了在信息课上快速开发而用*小熊猫*的情况下,对于**现有**排版方式感到不熟悉

**Comment by Ltabsyy** [comment]
代码按一下键自动排版是astyle的事，和小熊猫没关系。
你如果不喜欢自动缩进，自动补全括号的话，可以关。
![image](https://github.com/user-attachments/assets/da8def90-bd3a-40f1-a77d-1b92c208d675)
![image](https://github.com/user-attachments/assets/5a803dfe-7305-4c27-b1ad-8cc5f1cc3c63)

**Comment by LY-Xiang** [comment]
我所想表达的不是不要排版 而是想要Microsoft的排版格式
