### ISSUE TITLE
The editor does not supports triple-clicking the left mouse button to select an entire line | 编辑器不支持三击鼠标左键选择一整行

### ISSUE THREAD

**Issue by Dian-Jiao** [royqh1979/RedPanda-CPP#491]
This program is a fork from Dev-Cpp, while Dev-Cpp supports triple-clicking the left mouse button to select an entire line, and popular editor like Visual Studio Code,  Visual Studio and most of textbox are also supported.
This shortcut is common and important, please fix it.
Thanks.

这个程序作为 Dev-Cpp 的替代品我觉得很好用 :)，然而美中不足的是编辑器不支持三击鼠标选择一整行，这个快捷键无论是 Dev-Cpp，或者是现在主流的 VS、VSC，甚至大多数的文本框都支持。这个快捷键的很常用，请求添加对此快捷键的支持！
谢谢！

**Comment by Ltabsyy** [comment]
感觉选择整行只要在行首按下，移动到下一行行首，松开即可。可以一击+轻微移动实现，完全用不着三击

**Comment by royqh1979** [comment]
qt的事件处理系统中未提供鼠标三击事件，没有什么高效的方法来实现这个功能。
而目前在小熊猫C++可以（在未选中其他内容时）通过按ctrl+c 来选中当前行，通过三击来选中的意义也不是太大。
所以目前不会考虑这个功能。
