### ISSUE TITLE
写代码写着写着会闪退

### ISSUE THREAD

**Issue by songxingling1** [royqh1979/RedPanda-CPP#492]
Rt.代码如下：
```cpp
#include <bits/stdc++.h>
namespace SXL {
	using std::max;
	using std::min;
	using std::swap;
	constexpr int MAXN = 6000,MAXT = 30000;
	int dp[2][MAXT + 5];
	void main() {
		int n;
		scanf("%d",&n);
		int now = 0,last = 1;
		memset(dp[last],0x7f,sizeof(dp[last]));
		dp[last][0] = 0;
		for(int i = 1,a,b,c;i <= n;i++){
			scanf("%d%d%d",&a,&b,&c);
			memset(dp[now],0x7f,sizeof(dp[now]));
			for(int j = 0;j <= MAXT;j++) {
				if(a != 0 && j >= a) {
					dp[now][j] = min(dp[now][j],dp[last][j - a]);
				}
				if(b != 0) {
					dp[now][j] = min(dp[now][j],dp[last][j] + b);
				}
				if(c != 0 && j >= c) {
					dp[now][j] = min(dp[now][j],dp[last][j - c] + c);
				}
			}
			swap(now,last);
		}
		int ans = INT_MAX;
		for(int i = 0;i <= MAXT;i++){
			ans = min(ans,max(i,dp[last][i]));
		}
		printf("%d\n",ans);
	}
}
int main() {
	SXL::main();
	return 0;
}
```
如果一直不保存，写到 `printf("%d\n",ans);` 会闪退，也可能是概率性事件。

**Comment by ssunxiangrui** [comment]
> Rt.代码如下：
> 
> ```c++
> #include <bits/stdc++.h>
> namespace SXL {
> 	using std::max;
> 	using std::min;
> 	using std::swap;
> 	constexpr int MAXN = 6000,MAXT = 30000;
> 	int dp[2][MAXT + 5];
> 	void main() {
> 		int n;
> 		scanf("%d",&n);
> 		int now = 0,last = 1;
> 		memset(dp[last],0x7f,sizeof(dp[last]));
> 		dp[last][0] = 0;
> 		for(int i = 1,a,b,c;i <= n;i++){
> 			scanf("%d%d%d",&a,&b,&c);
> 			memset(dp[now],0x7f,sizeof(dp[now]));
> 			for(int j = 0;j <= MAXT;j++) {
> 				if(a != 0 && j >= a) {
> 					dp[now][j] = min(dp[now][j],dp[last][j - a]);
> 				}
> 				if(b != 0) {
> 					dp[now][j] = min(dp[now][j],dp[last][j] + b);
> 				}
> 				if(c != 0 && j >= c) {
> 					dp[now][j] = min(dp[now][j],dp[last][j - c] + c);
> 				}
> 			}
> 			swap(now,last);
> 		}
> 		int ans = INT_MAX;
> 		for(int i = 0;i <= MAXT;i++){
> 			ans = min(ans,max(i,dp[last][i]));
> 		}
> 		printf("%d\n",ans);
> 	}
> }
> int main() {
> 	SXL::main();
> 	return 0;
> }
> ```
> 
> 如果一直不保存，写到 `printf("%d\n",ans);` 会闪退，也可能是概率性事件。

显然是概率事件，怎么可能和你的代码有关啊

**Comment by songxingling1** [comment]
确实，但是这是BUG还是机器问题？
操作系统： Windows x64
内存大小：8GB
CPU：Intel(R) Pentium(R) CPU G870 @ 3.10GHz   3.10 GHz

**Comment by royqh1979** [comment]
用的小熊猫C++的版本号是多少

**Comment by royqh1979** [comment]
可能与 #477 有关
可以从本github仓库的actions里下载最新版试试
https://github.com/royqh1979/RedPanda-CPP/actions/workflows/build.yml 
翻页到最下方有下载链接
