### ISSUE TITLE
复制导出的HTML无法在WPS PPT正常粘贴

### ISSUE THREAD

**Issue by Ltabsyy** [royqh1979/RedPanda-CPP#493]
小熊猫C++导出的HTML高亮格式有问题，Office和WPS文字在进行纠错后可以正常粘贴，WPS PPT没做这个处理
(依稀提出)

**Comment by royqh1979** [comment]
有具体的格式错误信息吗？

**Comment by Ltabsyy** [comment]
据说是</html>标签没闭合
![QQ图片20240927112618](https://github.com/user-attachments/assets/7f65d4ed-78fe-4588-8822-0f875dac4547)

**Comment by yixy-only** [comment]
小熊猫 C++ 导出的 HTML 高亮格式遵循 XHTML 1.0 规范， 是否过于严格？毕竟只是导出高亮格式，其它软件能正确识别出高亮即可。如果其它软件严格遵守 XHTML 规范，识别导出内容时很容易因为一些不影响整体的微小差错而无法正确识别。

**Comment by royqh1979** [comment]
> 小熊猫 C++ 导出的 HTML 高亮格式遵循 XHTML 1.0 规范， 是否过于严格？毕竟只是导出高亮格式，其它软件能正确识别出高亮即可。如果其它软件严格遵守 XHTML 规范，识别导出内容时很容易因为一些不影响整体的微小差错而无法正确识别。

导出的内容严格遵守规范，其他软件导入时应该更容易识别才对呀。

**Comment by royqh1979** [comment]
应该不是这个问题
> 据说是标签没闭合 ![QQ图片20240927112618](https://private-user-images.githubusercontent.com/111294086/371380865-7f65d4ed-78fe-4588-8822-0f875dac4547.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0ODUwOTIsIm5iZiI6MTcyNzQ4NDc5MiwicGF0aCI6Ii8xMTEyOTQwODYvMzcxMzgwODY1LTdmNjVkNGVkLTc4ZmUtNDU4OC04ODIyLTBmODc1ZGFjNDU0Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwMDUzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzNmOTFjMGUwYTYxMzk0YjM1YjFmMWE4OThlZWUzMjExZWM3ZWI1NDI0YzNhN2JlOGVhMDBlMTZmZmM0MTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L7_wVKdTkFImht33Qw5E7a6235cjFkoMZTU_1N4vBZ4)

**Comment by yixy-only** [comment]
> 导出的内容严格遵守规范，其他软件导入时应该更容易识别才对呀。

不是这个意思，如果内容里直接声明符合 XHTML 1.0 规范，那软件就会按照 XHTML 的严格标准来验证生成的内容，一点微小差错就会导致不符合规范而验证失败。

相反，本身按照高要求的 XHTML 来写，但是在内容里声明的是 HTML 规范，软件就会按照 HTML 的宽松规范来验证内容，并且会尝试纠错，出错的可能性大大减小。

**Comment by royqh1979** [comment]
vscode复制的内容在wps 2019的演示里也无法带格式粘贴。

**Comment by Ltabsyy** [comment]
现在已经可以粘贴了，WPS演示的粘贴不能在文本框里粘贴，而应该直接粘贴，这样就是有颜色的。不过会变成字体大小只有1的竖条，需要之后自己调整一下。
![屏幕截图 2024-10-04 180054](https://github.com/user-attachments/assets/1ea31971-3b18-4ed4-b20c-e3b1caa8d94f)

**Comment by Ltabsyy** [comment]
目前WPS PPT的bug已然修复，字体大小1竖条的问题被暂时认为是WPS PPT的问题，故关闭此issue。如需继续优化代码的复制/导出，可考虑重启#439。该issue已根据最新版本补充自适应行号列宽需求。
