### ISSUE TITLE
导入文件的试题案例过大导致界面卡顿和显示错误

### ISSUE THREAD

**Issue by Alan-CRL** [royqh1979/RedPanda-CPP#502]
应对导入的文件大小做限制，大于一定大小的文件不应该显示（可以加个文件过大不显示的提示），否则页面会变得非常卡顿。

![RedPandaIDE_B04cmYLL2m](https://github.com/user-attachments/assets/49640605-6637-4c44-afcf-3226b7e5e32b)

**Comment by royqh1979** [comment]
解决方案1： 用户可自行切换显示/不显示 + 内容较长时自动切换为不显示。主要的问题是在界面上如何安排相关控制的按钮
解决方案2：内容较长时只显示出错的位置+前后的部分内容

是否还有其它的方案？

**Comment by Alan-CRL** [comment]
可以将方案一和二融合一下，并提供选项。对于大文件的测试，想必用户也是为了测试，而不是为了查看并 debug，所以用户应该更需要的是 输出 和 期望输出 的查看，而大文件的输入块则可以选择隐藏或选择使用方案二。
