### ISSUE TITLE
是否有可能添加对其他编译器的支持，例如MSVC？

### ISSUE THREAD

**Issue by Moyv-Wang** [royqh1979/RedPanda-CPP#524]
MinGW编译器有一些行为似乎并不遵循标准，例如：
int main(void) {
    int sz = 5;
    int arr[sz];
}
这在C++ 11标准中是不支持的，声明数组时其长度必须是常量或字面值，但MinGW并不会报错，因为GCC对其进行了优化，允许使用VLA扩展。但在MSVC编译器下编译会报错，但小熊猫C++似乎只支持GCC编译器，未来是否会考虑添加支持呢？
感谢！

**Comment by royqh1979** [comment]
暂时无此计划
用VC编译器但是不用其IDE的人非常少
