### ISSUE TITLE
In RedPandaIDE-3.1.2872 and 3.0.2814, reformatting the code causes the file to fail to compile! 格式化后无法编译！

### ISSUE THREAD

**Issue by wudannee** [royqh1979/RedPanda-CPP#526]
- OS版本： `ubuntu 22.04`
- IDE版本：`RedPandaIDE-3.1.2872`  `RedPandaIDE-3.0.2814`
- 下载地址：https://github.com/redpanda-cpp/linux-generic/releases/download/v3.1/RedPandaIDE-3.1.2872-x86_64.AppImage
- 下载地址：https://github.com/redpanda-cpp/linux-generic/releases/download/v3.0/RedPandaIDE-3.0.2814-x86_64.AppImage

**格式化代码以后会导致无法编译，查看了“代码排版”->“通用”，发现“预定义排版方案”中里也多了一行字， “Cannot set native locale, reverting to English”**

![image](https://github.com/user-attachments/assets/fd4a789a-0876-4efb-b22a-1992b2b21214)

![image](https://github.com/user-attachments/assets/1eab8774-e186-4ea9-8d24-23747edfd19f)

**Comment by wudannee** [comment]
- OS Version: `ubuntu 22.04`
- IDE Version: `RedPandaIDE-3.1.2872`  `RedPandaIDE-3.0.2814`
- Download Link: https://github.com/redpanda-cpp/linux-generic/releases/download/v3.1/RedPandaIDE-3.1.2872-x86_64.AppImage
- Download Link: https://github.com/redpanda-cpp/linux-generic/releases/download/v3.0/RedPandaIDE-3.0.2814-x86_64.AppImage

**After formatting the code, it leads to a compilation failure. I checked the "Code Formatting" -> "General" section, and found that an extra line has appeared in the "Predefined Formatting Scheme" saying, "Cannot set native locale, reverting to English."**

![image](https://github.com/user-attachments/assets/fd4a789a-0876-4efb-b22a-1992b2b21214)

![image](https://github.com/user-attachments/assets/1eab8774-e186-4ea9-8d24-23747edfd19f)

### `Version 2.26` does not have this issue: `https://github.com/redpanda-cpp/linux-generic/releases/download/v2.26/RedPandaIDE-2.26-x86_64.AppImage`

**Comment by Ltabsyy** [comment]
这是因为astyle乱加Cannot set native locale, reverting to English，3.2最新版已经修复，等3.2正式版出吧

**Comment by wudannee** [comment]
> 这是因为astyle乱加Cannot set native locale, reverting to English，3.2最新版已经修复，等3.2正式版出吧

好的，谢谢

我安装的版本 `Artistic Style Version 3.1` ，单独使用`astyle`来格式化代码并没有发现有乱加 `Cannot set native locale, reverting to English`的情况，集成到小熊猫使用就出现上述问题了

**Comment by wudannee** [comment]
`3.2.2958` 格式化代码正常了，但是有新问题
https://github.com/royqh1979/RedPanda-CPP/issues/530
