### ISSUE TITLE
Add OEM Codepages (CP866, etc)

### ISSUE THREAD

**Issue by melkorbsd** [royqh1979/RedPanda-CPP#534]
Please, add codepage CP866 (and other OEM codepages).

The OEM code pages are historically used by Windows Console applications.

The klist of Windows OEM codepages:
437 (US)
720 (Arabic)
737 (Greek)
775 (Baltic)
850 (Multilingual Latin I)
852 (Latin II)
855 (Cyrillic)
857 (Turkish)
858 (Multilingual Latin I + Euro)
862 (Hebrew)
866 (Russian)

**Comment by royqh1979** [comment]
Do you mean add more charsets to options / compiler /  compiler set / "Convert Executable's Charset as " combobox?
I need to know their corresponding names used by iconv.

**Comment by royqh1979** [comment]
@CyanoHao Continue the discussion here.

from wikipedia (https://en.wikipedia.org/wiki/Windows_code_page)

> A typical OEM code page, in its second half, does not resemble any ANSI/Windows code page even roughly. Nevertheless, two single-byte, fixed-width code pages (874 for [Thai](https://en.wikipedia.org/wiki/Thai_language) and 1258 for [Vietnamese](https://en.wikipedia.org/wiki/Vietnamese_language)) and four multibyte [CJK](https://en.wikipedia.org/wiki/CJK_characters) code pages ([932](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)), [936](https://en.wikipedia.org/wiki/Code_page_1386), [949](https://en.wikipedia.org/wiki/Windows-949), [950](https://en.wikipedia.org/wiki/Windows-950)) are used as both OEM and ANSI code pages. Code page 1258 uses [combining diacritics](https://en.wikipedia.org/wiki/Combining_diacritic), as Vietnamese requires more than 128 letter-diacritic combinations. This is in contrast to [VISCII](https://en.wikipedia.org/wiki/VISCII), which replaces some of the [C0](https://en.wikipedia.org/wiki/C0_control_codes) (i.e. ASCII) control codes.

So it seems that we does need these OEM codepage.

And maybe we could have a better solution, a lookup table between  ansi codepage and its corresponding oem codepage, and user don't need to choose it themself?

**Comment by royqh1979** [comment]
> @CyanoHao Continue the discussion here.
> 
> And maybe we could have a better solution, a lookup table between ansi codepage and its corresponding oem codepage, and user don't need to choose it manually?

En, what we should do here is use OEMCP instead of ActiveCP for gcc -fexec-charset. No need for lookup table.

**Comment by royqh1979** [comment]
@melkorbsd Can you please test the newest version?
Use system's oem code page instead of ansi codepage for gcc's -fexec-charset option

**Comment by CyanoHao** [comment]
Assumption: In Windows programming or cross-platform programming, directly passing non-ASCII literals to APIs (where auto charset conversion takes effect) only appears in beginners' programs or casual programs. Advanced developers never do such thing in formal programs.

For compiler output, I group encodings into 5 groups, order by usefulness (in my opinion):
1. System ACP
   - This is the most common case for interoperability.
2. System OEMCP
   - In European languages, Arabic, and Hebrew, console-I/O-only programs can run WYSIWYG.
   - Standard library file I/O and Win32 `-A` APIs respect system ACP. Using system OEMCP breaks these functions.
3. Other possible ACP
   - Useful when auto detection is not available (e.g. WSL or normal Linux installation).
4. Other possible OEMCP
   - Have to explicitly set console encoding. But why not set it to UTF-8?
5. Other encodings
   - Never use them.

I think it's okay to leave only 2 (or 3) options in execution charset: system ACP, and system OEMCP (or plus UTF-8).

More aggressively, encoding can be simplified by:
- Removing all encoding features (incl. editor encoding and execution charset) on non-Windows host (and even more, Windows in UTF-8);
- Removing execution charset for non-Windows or Windows ARM64 target.

**Comment by royqh1979** [comment]
> More aggressively, encoding can be simplified by:
> 
> * Removing all encoding features (incl. editor encoding and execution charset) on non-Windows host (and even more, Windows in UTF-8);

As a general code edit widget, qsynedit needs encoding support.

> * Removing execution charset for non-Windows or Windows ARM64 target.

Not sure. Maybe we need it for cross-compiling?

**Comment by melkorbsd** [comment]
> @melkorbsd Can you please test the newest version? Use system's oem code page instead of ansi codepage for gcc's -fexec-charset option

3.3.3024: Default settings is:

[x] Convert Executable's charset as [System Default] (detected as windows-1251)

Also detected [System OEM) (as cp866)

![изображение](https://github.com/user-attachments/assets/c57dfcb2-a114-4636-8415-4f17c2da462d)
