### ISSUE TITLE
Extension of RedPanda IDE

### ISSUE THREAD

**Issue by kapil-iitk** [royqh1979/RedPanda-CPP#536]
Thank you for this excellent IDE that I am using for C/C++ programming. Can you please suggest what changes I can make so that I can use this for Fortran programming (gfortran)?

**Comment by royqh1979** [comment]
If you don't need code completion / code intellisense, that will not be too hard, maybe.

For syntax color:
1. Add a new syntaxer for fortran. You can find syntaxer definitions in libs/qsynedit/syntaxer. 
2. Register the syntaxer to syntaxmanager

For compile & run:
You can search ENABLE_SDCC in codes to see how the sdcc compiler is supported. Basiclly you need to :
1. Create a new compiler class to modify the existing one to use gfortran to compile
2. in mainwindow's compile / run / debug methods, add fortran file suffix to the switch that decide if the current file is compile/run/debug-able.
3. in mainwindow's updateCompileActions(), modify checks that disable the menu actions if current file is not compile/run/debug-able.
