### ISSUE TITLE
Major memory leaks since at least v1.4

### ISSUE THREAD

**Issue by bitwisexornot** [royqh1979/RedPanda-CPP#72]
I have found leaving the IDE open for hours it can consume up to 18.8 GB memory. Sometimes around 8GB it crashes. I use the find/replace all in project feature extensively (over 100 per session) and compile maybe 20 times an hour. Merging several code bases. This is how I discovered the cross bookmarks issue and losing them in crashes or maybe memory was being over written?

**Comment by royqh1979** [comment]
Can you provide more details about your usage, like:
How many files in your project?
What's the memory usage after you open your project?

I can't see why it uses so many memories.

**Comment by bitwisexornot** [comment]
Sorry for the delay. I leave the editor open for 8+ hours day since using it. There are about 20 C files in each (compiled binary is 1MB, so not huge LOC). I rarely use the "Structure" tab, that was a problem in DevCpp (plus it tends to jump to declaration rather than function.)

I tend to use find all in project a lot. I mostly see the "Issues" tab on bottom constantly recompiling (syntax) my code, including if I have several code file tabs open, it will re-do them even if inactive.

Memory usage after opening project is 500mb. Right now, the IDE has been open 24 hours, with over 100 builds (small changes to large logic system) and is using 3.5GB memory. I am on Win10 x64/Ryzen/32gb RAM.

I think you have memory leaks in the GCC build/display, the file find, and maybe the auto-code parser as I use these the most. 

It would be nice if the IDE would not force rebuilding open tabs, or re-parse inactive unchanged tabs in background. This is occurring all the time when working, not just on active tab with line changes. 

Marking tabs as unchanged and not parsing would be helpful (might help clue in on if that has anything to do with it. I have to se GCC to -O0 because of all the recompiling, which is why I think there are leaks in that area, find all in project, and maybe the code parser.

Great IDE. I will be happy to answer any questions. Whatever my usage pattern is, I can balloon the memory every day so will be happy to beta test versions.

If you want to add logging for usage/program statistics I would be happy to send data.

PS. Since this is cross-platform, you might consider running the Valgrind tool to find information. https://valgrind.org/docs/manual/quick-start.html

**Comment by bitwisexornot** [comment]
I have been using v2.1 since release, and am glad to report I have seen no unusual memory usage. The IDE stays around 250-350mb from when I have been checking. No growing usage when away from computer, or during my normal usage. I will watch this, though so far it seems you totally eliminated the memory leak. RAM usage seems very stable now.

**Comment by bitwisexornot** [comment]
No longer experience this memory leak issue, RedPanda memory usage seems stable at around 250-350mb for my usage.
