### ISSUE TITLE
重命名文件时不选择后缀部分

### ISSUE THREAD

**Issue by yzqzss** [royqh1979/RedPanda-CPP#73]
小熊猫重命名文件时会默认全选文件名和后缀。
![image](https://user-images.githubusercontent.com/30341059/194831262-611c8f08-3678-46c7-855d-7ae60ea99ed9.png)

这是 VSC 的重命名，默认仅选择文件名，比较方便：
![image](https://user-images.githubusercontent.com/30341059/194830001-82bcdf12-1962-40bc-8cdb-05dcc42fd62b.png)

---
Ver: 小熊猫 1.4

**Comment by royqh1979** [comment]
这个提议很好。但是实现起来需要深入研究QT内置的QTreeView控件的工作机制，暂时不会考虑做这个。

**Comment by yzqzss** [comment]
> 这个提议很好。但是实现起来需要深入研究QT内置的QTreeView控件的工作机制，暂时不会考虑做这个。

好的，感谢作者！

---
~~小熊猫对新手真的很好用，我已经成功忽悠我们班老师从 VS2010/Dev C++ 这些陈年 IDE 换成小熊猫了，现在我们班就在用小熊猫 C++ 来上课！xD~~

**Comment by XY0797** [comment]
> 小熊猫重命名文件时会默认全选文件名和后缀。 ![image](https://user-images.githubusercontent.com/30341059/194831262-611c8f08-3678-46c7-855d-7ae60ea99ed9.png)
> 
> 这是 VSC 的重命名，默认仅选择文件名，比较方便： ![image](https://user-images.githubusercontent.com/30341059/194830001-82bcdf12-1962-40bc-8cdb-05dcc42fd62b.png)
> 
> Ver: 小熊猫 1.4

目前的小熊猫发行版本已经有了这个功能，此issues可以关闭了
