### ISSUE TITLE
Code windows do not consistently detect changes to text anymore

### ISSUE THREAD

**Issue by bitwisexornot** [royqh1979/RedPanda-CPP#76]
I can type in a tab, or crtl+/ to comment out something (ie, no direct typing), either way the IDE since v2.1 does not always put an asterisk to indicate file changed. It will not recompile the file until I add or delete spaces to trigger the asterisk. Cannot save, compile or even undo during this program condition. 

This bug also misleads (as a detail I cannot recall whether it will compile a file as unchanged) me into believing a file has been recompiled as the IDE often does several files (common header?), so I end up having to recompile the whole project because of strange bugs from one object file with old information not updating. This problem occurs in both 32bit and x64 versions.

**Comment by bitwisexornot** [comment]
The event that alerted me to this issue was that I accidentally hit a key with code highlighted and deleted the block --- but crtl-z would not work! There was no asterisk and I was sure I saved the file and somehow lost undo. But the file closed without asking to save (it was modified), and when re-opened was the original file. I'm not sure it would let me save. But losing undo was a surprise!

**Comment by bitwisexornot** [comment]
This also prevents other project files affected from "changes" not recorded by program (*) to be compiled. I can hit spaces and returns and watch the (*) appear and disappear from the tab. Even with the (*) other project files (sometimes ones included by header changed) do not recompile and I have to rebuild the entire project between some changes. Bad bug.

**Comment by bitwisexornot** [comment]
Unfortunately, this has become a real usability issue. I can hit space and have the file pretend there were NO prior changes (ie, lose work, because you cannot undo last operation --- IDE thinks file is original). The further problem is that RedPanda will not rebuild all the files touched as it thinks some are unchanged. I don't know if in the past you rebuilt everything connected to a common header, but that is now broken. SO I am often left using F12 and rebuild world after more than a couple hours wasted time wondering why changes in my program either werent taking, or were and there were weird new crashes (from source that didn't rebuild holding old functions, vars, etc.). I know I give a lot of feedback as I enjoy this IDE --- this bug needs an out-of-monthly cycle hotfix please. I think the parser is messing up on forwards and backwards, gives wrong syntax errors after recompile, and I think the indenting is screwy with the forward/backward deletes, tabs. For an example of data loss, I was working on a file for 5 minutes, accidentally hit crtl+/ to comment a block, instead hit period and lost the block of code as the IDE would not le me undo (thought file was unchanged still, despite * on and off) ... I had to close the file and hope everything since the last save was still like it was --- and it was. It let me close the altered file with no save dialog and discarded all the changes since the save several minutes prior. So you lose undo and reliable compiling/syntax checks. Thanks for all the hard work, you really spend a lot of time developing this and I look forward to using more features than the debugger (nice).

**Comment by royqh1979** [comment]
I'll investigate it. 

For now, files without modified flag can be saved with File / save

**Comment by royqh1979** [comment]
It seems that there's some error in the calculation of undo's memory usage.

**Comment by royqh1979** [comment]
Fixed in version 2.1

**Comment by bitwisexornot** [comment]
This issue is fixed.
