### ISSUE TITLE
无法取消在文件行数或光标所在行变化时的自动语法检查

### ISSUE THREAD

**Issue by humanoid-konjac** [royqh1979/RedPanda-CPP#79]
将“设置 > 编辑器 > 自动语法检查 > 在文件行数或者光标所在行变化时检查”前的勾取消并应用更改后移动光标所在的行仍旧会进行自动语法检查。

即使重启小熊猫也无法使得该更改生效。

不知道这个BUG能否在您的电脑上复现，感谢您的贡献！

**Comment by royqh1979** [comment]
fixed in 2.4
